versions:
  "2.4.7.1":
    folder: all
  "2.4.17.0":
    folder: all
  "2.5.14.0":
    folder: all
  "2.5.15.0":
    folder: all
  "2.5.16.0":
    folder: all
  "2.5.17.0":
    folder: all
  "2.5.18.0":
    folder: all

