versions:
  "1.5.0":
    folder: "all"
  "1.4.3":
    folder: "all"
  "1.3.0":
    folder: "all"
  "1.2.0":
    folder: "all"
  "1.1.1":
    folder: "all"
  "1.0.1":
    folder: "all"
  "0.28.5":
    folder: "0.28.x"
  "0.27.10":
    folder: "0.27.x"
