versions:
  "1.19.0":
    folder: all
  "1.18.0":
    folder: all
  "1.17.0":
    folder: all
  "1.16.0":
    folder: all
  "1.15.0":
    folder: all
  "1.14.0":
    folder: all
  "1.12.0":
    folder: all
  "1.8.0":
    folder: all
  "1.7.0":
    folder: all
