versions:
  "4.4.0":
    folder: all
  "4.3.1":
    folder: all
  "4.3.0":
    folder: all
  "4.1.2":
    folder: all
  "4.1.0":
    folder: all
  "4.0.4":
    folder: all
  "4.0.1":
    folder: all
  "4.0.0":
    folder: all
  "3.1.1":
    folder: all
  "3.1.0":
    folder: all
  "3.0.2":
    folder: all
  "2.0.1":
    folder: all
  "1.4.0":
    folder: all
  "1.3.3":
    folder: all
