versions:
  "1.3.5":
    folder: "all"
  "2.0.0":
    folder: "all"
  "2.0.1":
    folder: "all"
  "2.0.2":
    folder: "all"
  "2.0.3":
    folder: "all"
  "2.0.5":
    folder: "all"
  "2.0.6":
    folder: "all"
