---
# Configuration for `https://github.com/conan-io/conan-center-index` repository
id: 'conan-io/conan-center-index'

conan:
  version: 1.64.1

artifactory:
  url: "https://c3i.jfrog.io/c3i"
  main_repo: "conan-center"
  pull-request_repo_prefix: "c3i_PR"
  pull-request_permission: "c3i-pr"
  logs_repo: "misc"
  cache_repo: "cache"

github:
  reviewers: "reviewers.yml"
  authorized_users: "authorized_users.yml"
  waitlist_users: "waitlist_users.yml"

slack:
  credential_success_url: SLACK_SUCCESS_WEBHOOK_URL
  ceredential_errors_url: SLACK_FAILURE_WEBHOOK_URL

# Things related to Jenkins jobs
tasks:
  access_request:
    request_issue_url: https://github.com/conan-io/conan-center-index/issues/4
    max_inactivity_days: 0
  automatic_merge:
    reviews_required_total: 2  # Reviews that a PR needs so it can be merged
    reviews_required_team: 1  # Reviews from the Conan team that a PR needs so it can be merged
    reviews_required_bump: 1  # Total reviews required for a bump PR to be merged
    branches:  # PRs from automations that have these as base-branches will be merged automatically
      - "conan-io:action-doc-toc"
    # Requirements to merge a given pull-request:
    # * check_runs refers to notifications from GH actions
    # * status_checks refers to notifications coming from external tools (Jenkins, CLA,...)
    status_checks:
      - name: "license/cla"
      - name: "continuous-integration/jenkins/pr-merge"
      - name: "c3i/conan-v2/pr-merge"
  build_single_reference:
    package_id_cache_type: "none"
    timeout_minutes: 600
    large_timeout_minutes: 900
    large_timeout_references:
      - boost
      - qt
      - llvm
    parallel_strategy: unlimited
  cci:
    conan_v2_run_export: false
    write_comments: true
    detailed_status_checks: false
    update_labels: true
    build_bump_deps_pr: false
    description_bump_deps_pr: ":vertical_traffic_light: Thank for your Bump dependencies PR. The build service will be triggered soon by a Conan team member."
    wait_for_multibranch:  # CCI jobs should wait for other multibranch job for that same PR
      job_name: "prod-v2/cci"  # e.g. "cci-v2/cci" -> this means waiting for cci-v2/cci/PR-<number>
      timeout_seconds: 600  # Maximum time to wait for the multibranch job
      merge_messages: true  # Merge messages from the multibranch job waited for
      merge_labels: true  # Merge labels from the multibranch job waited for
  job_relauncher:
    job_names:
      - prod-v1/cci
      - prod-v2/cci
  scheduled_export_check:
    report_issue_url: https://github.com/conan-io/conan-center-index/issues/20516
    report_issue_append: false
  validate_infrastructure:
    macos_executors: 2
    windows_executors: 4
    create_docs_pull-request: true

# Profile configurations to build packages
configurations:
  - id: linux-gcc-legacy
    hrname: "Linux, GCC-legacy"
    content:
      - os: ["Linux"]
        arch: ["x86_64"]
        compiler:
          - "gcc":
              compiler.libcxx: [ "libstdc++11" ]
              compiler.version: ["5", "7", "9"]
              build_type: ["Release"]
  - id: linux-gcc11
    hrname: "Linux, GCC11"
    content:
      - os: ["Linux"]
        arch: ["x86_64"]
        compiler:
          - "gcc":
              compiler.libcxx: [ "libstdc++11" ]
              compiler.version: ["11"]
              build_type: ["Release", "Debug"]
  - id: linux-clang
    hrname: "Linux, Clang"
    content:
      - os: ["Linux"]
        arch: ["x86_64"]
        compiler:
          - "clang":
              compiler.libcxx: ["libstdc++", "libc++"]
              compiler.version: ["13"]
              build_type: ["Release"]
  - id: macos-m1-clang
    hrname: "macOS, Clang (M1/arm64)"
    content:
      - os: [ "Macos" ]
        arch: [ "armv8" ]
        compiler:
          - "apple-clang":
              compiler.version: [ "13.0" ]
              compiler.libcxx: [ "libc++" ]
              build_type: [ "Release", "Debug" ]
  - id: windows-visual_studio
    hrname: "Windows, Visual Studio"
    content:
      - os: [ "Windows" ]
        arch: [ "x86_64" ]
        compiler:
          - "Visual Studio":
              compiler.version: [ "16" ]
              build_type:
                - "Release":
                    compiler.runtime: [ "MD" ]
                - "Debug":
                    compiler.runtime: [ "MDd" ]

jenkins:
  url: "http://mb-jenkins-my-bloody-jenkins:8080"

node_labels:
  Windows:
    x86_64:
      "Visual Studio":
        default: "windows20230531"
  Macos:
    x86_64:
      "apple-clang":
        default: "mac_apple_clang_${compiler.version}"
    armv8:
      "apple-clang":
        default: "mac_apple_clang_${compiler.version}"
  Linux:
    x86_64:
      "gcc":
        default: "linux_gcc_${compiler.version}"
        "11": "linux_gcc_${compiler.version}_ubuntu16.04"
      "clang":
        default: "linux_clang_${compiler.version}_ubuntu16.04"
        "11": "linux_clang_${compiler.version}"

pod_size:
  # Map with references that need special memory resources to compile.
  #   - Can be only by name or by name/version.
  #   - name/version notation takes preference over the name only one
  #   - Both notations can be combined for the same reference name
  large:
    - "duckdb"
    - "ceres-solver"
    - "simd"
  xlarge:
    - "llvm"
    - "opengv"
    - "pcl"
