versions:
  "2.0.0":
    folder: "all"
  "1.12.0":
    folder: "all"
  "1.11.0":
    folder: "all"
  "1.9.0":
    folder: "all"
  "1.6.1":
    folder: "all"
  "1.5.0":
    folder: "all"
  "1.4.0":
    folder: "all"
  "1.2.0":
    folder: "all"
  "1.1.0":
    folder: "all"
