versions:
  "7.12.3":
    folder: all
  "7.11.2":
    folder: all
  "7.10.3":
    folder: all
  "7.9.3":
    folder: all
  "7.8.0":
    folder: all
  "7.7.7":
    folder: all
  "7.6.0":
    folder: all
  "7.5.0":
    folder: all
