versions:
  "0.2.2":
    folder: all
  "0.2.1":
    folder: all
  "0.2.0":
    folder: all
  "0.1.11":
    folder: all
  "0.1.10":
    folder: all
  "0.1.9":
    folder: all
  "0.1.8":
    folder: all
