versions:
  "1.3.0":
    folder: "all"
  "1.3.1":
    folder: "all"
  "1.3.4":
    folder: "all"
  "1.3.5":
    folder: "all"
  "1.3.6":
    folder: "all"
  "1.3.8":
    folder: "all"
  "1.3.9":
    folder: "all"
  "1.3.10":
    folder: "all"
