versions:
  "4.3.3":
    folder: "all"
  "4.3.0":
    folder: "all"
  "4.2.7":
    folder: "all"
  "4.2.5":
    folder: "all"
  "4.2.0":
    folder: "all"
  "4.1.1":
    folder: "all"
  "4.0.0":
    folder: "all"
  "3.2.1":
    folder: "all"
  "3.1.0":
    folder: "all"
  "3.0.2":
    folder: "all"
  "2.3.0":
    folder: "all"
  "2.2.0":
    folder: "all"
  "2.1.1":
    folder: "all"
