versions:
  "2.5.1":
    folder: "all"
  "2.2.0":
    folder: "all"
  "2.1.0":
    folder: "all"
  "2.0.3":
    folder: "all"
  "1.9.5":
    folder: "all"
  "1.9.3":
    folder: "all"
  "1.7.4":
    folder: "all"
