versions:
  "0.22.6":
    folder: all
  "0.22.5":
    folder: all
  "0.22.1":
    folder: all
  "0.21.0":
    folder: all
  "0.20.8":
    folder: all
  "0.20.6":
    folder: all
  "0.20.0":
    folder: all
  "0.17.3":
    folder: all
