versions:
  "0.25.1":
    folder: all
  "0.24.4":
    folder: all
  "0.24.3":
    folder: all
  "0.23.1":
    folder: all
  "0.23.0":
    folder: all
  "0.22.6":
    folder: all
  "0.22.5":
    folder: all
  "0.22.1":
    folder: all
  "0.21.0":
    folder: all
  # keep 0.20.8 for tree-sitter-c
  "0.20.8":
    folder: all
