versions:
  "1.2.5":
    folder: all
  "1.2.3":
    folder: all
  "1.2.2":
    folder: all
  "1.2.0":
    folder: all
  "1.1.2":
    folder: all
  "0.3.6":
    folder: all
  "0.3.5":
    folder: all
  "0.3.2":
    folder: all
  "0.2.2":
    folder: all
  "0.2.1":
    folder: all
  "0.2.0":
    folder: all
  "0.1.8":
    folder: all
  "0.1.7":
    folder: all
  "0.1.4":
    folder: all
  "0.0.7":
    folder: all
