versions:
  "1.3.2":
    folder: all
  "1.3.1":
    folder: all
  "1.3.0":
    folder: all
  "1.2.6":
    folder: all
  "1.2.5":
    folder: all
  "1.2.3":
    folder: all
  "1.2.2":
    folder: all
  "1.2.0":
    folder: all
  "1.1.2":
    folder: all
  "0.3.6":
    folder: all
  "0.2.2":
    folder: all
