versions:
  "2.8.4":
    folder: all
  "2.8.2":
    folder: all
  "2.8.1":
    folder: all
  "2.8.0":
    folder: all
  "2.7.0":
    folder: all
  "2.6.9":
    folder: all
  "2.6.6":
    folder: all
  "2.6.5":
    folder: all
  "2.6.4":
    folder: all
  "2.6.3":
    folder: all
  "2.6.2":
    folder: all
  "2.1.6":
    folder: all
