versions:
  "2.0.6":
    folder: all
  "2.0.5":
    folder: all
  "2.0.3":
    folder: all
  "2.0.2":
    folder: all
  "2.0.1":
    folder: all
  "2.0.0":
    folder: all
  "1.9.9":
    folder: all
  "1.9.8.1":
    folder: all
  "1.9.5":
    folder: all
  "1.8.5":
    folder: all
  "1.8.4":
    folder: all
  "1.8.3":
    folder: all
  "1.8.2":
    folder: all
  "1.8.1":
    folder: all
  "1.7.0":
    folder: all
  "1.6.1":
    folder: all
