versions:
  "5.3.0":
    folder: all
  "5.0.2":
    folder: all
  "5.0.0":
    folder: all
  "4.4.3":
    folder: all
  "4.3.1":
    folder: all
  "4.0.1":
    folder: all
  "3.6.2":
    folder: all
  "3.6.1":
    folder: all
  "3.4.3":
    folder: all
  "3.4.1":
    folder: all
  "3.3.4":
    folder: all
  "3.3.2":
    folder: all
  "3.3.1":
    folder: all
  "3.1.9":
    folder: all
  "3.1.7":
    folder: all
  "2.9.5":
    folder: all
  "2.8.4":
    folder: all
