versions:
  "2.6.6":
    folder: all
  "2.6.5":
    folder: all
  "2.6.4":
    folder: all
  "2.6.3":
    folder: all
  "2.6.2":
    folder: all
  "2.6.1":
    folder: all
  "2.6.0":
    folder: all
  "2.5.5":
    folder: all
  "2.5.4":
    folder: all
  "2.5.3":
    folder: all
  "2.4.0":
    folder: all
  "2.3.2":
    folder: all
  "2.3.1":
    folder: all
  "2.3.0":
    folder: all
  "2.2.1":
    folder: all
  "2.1.9":
    folder: all
  "2.1.6":
    folder: all
  "2.0.9":
    folder: all
