versions:
  "2.1.0":
    folder: all
  "2.0.9":
    folder: all
  "2.0.7":
    folder: all
  "2.0.6":
    folder: all
  "2.0.5":
    folder: all
  "2.0.3":
    folder: all
  "2.0.2":
    folder: all
  "2.0.1":
    folder: all
  "2.0.0":
    folder: all
  "1.9.9":
    folder: all
  "1.9.5":
    folder: all
  "1.8.5":
    folder: all
