versions:
  "3.1.10":
    folder: all
  "3.1.9":
    folder: all
  "3.1.8":
    folder: all
  "3.1.7":
    folder: all
  "3.1.6":
    folder: all
  "3.1.5":
    folder: all
  "3.1.4":
    folder: all
