versions:
  "1.0":
    folder: "all"
  "1.1":
    folder: "all"
  "1.2":
    folder: "all"
  "1.3":
    folder: "all"
  "1.4":
    folder: "all"
  "1.4.1":
    folder: "all"
  "1.4.2":
    folder: "all"
