versions:
  "4.10.1":
    folder: all
  "4.06.1":
    folder: all
  "4.03.1":
    folder: all
  "4.02.1":
    folder: all
  "4.01.9":
    folder: all
  "4.01.7":
    folder: all
  "4.01.5":
    folder: all
