versions:
  "1.19":
    folder: "all"
  "1.18":
    folder: "all"
  "1.17":
    folder: "all"
  "1.15":
    folder: "all"
  "1.14":
    folder: "pre_1.15"
  "1.12":
    folder: "pre_1.15"
  "1.10":
    folder: "pre_1.15"
  "1.9":
    folder: "pre_1.15"
  "1.8":
    folder: "pre_1.15"
  "1.7":
    folder: "pre_1.15"
