versions:
  "3.7.0":
    folder: "all"
  "3.6.0":
    folder: "all"
  "3.5.1":
    folder: "all"
  "3.5.0":
    folder: "all"
  "3.4.1":
    folder: "all"
  "3.4.0":
    folder: "all"
  "3.3.1":
    folder: "all"
  "3.2.0":
    folder: "all"
  "3.1.0":
    folder: "all"
  "3.0.2":
    folder: "all"
  "2.9.2":
    folder: "all"
  "2.9.1":
    folder: "all"
  "2.9.0":
    folder: "all"
  "2.8.0":
    folder: "all"
  "2.7.0":
    folder: "all"
  "2.6.0":
    folder: "all"
  "1.7.3":
    folder: "all"
