versions:
  "1.2.3":
    folder: "all"
  "1.3.1":
    folder: "all"
  "1.3.2":
    folder: "all"
  "1.3.3":
    folder: "all"
  "1.4.0":
    folder: "all"
  "1.5.2":
    folder: "all"
  "1.6.0":
    folder: "all"
  "1.6.1":
    folder: "all"
  "1.6.2":
    folder: "all"
  "1.6.3":
    folder: "all"
