versions:
  "9.0.2":
    folder: "all"
  "8.2.0":
    folder: "all"
  "8.1.0":
    folder: "all"
  "7.5.0":
    folder: "all"
  "7.4.0":
    folder: "all"
  "7.3.0":
    folder: "all"
  "7.2.2":
    folder: "all"
  "7.2.1":
    folder: "all"
  "7.1.0":
    folder: "all"
  "6.1.0":
    folder: "all"
  "6.0.0":
    folder: "all"
  "4.5.0":
    folder: "all"
  "4.4.1":
    folder: "all"
