versions:
  "6.1.9":
    folder: all
  "6.0.2":
    folder: all
  "5.0.0":
    folder: all
  "4.1.1":
    folder: all
  "4.1.0":
    folder: all
  "4.0.0":
    folder: all
  "3.0.0":
    folder: all
  "2.0.0":
    folder: all
