versions:
  "1.27.0":
    folder: all
  "1.26.0":
    folder: all
  "1.25.0":
    folder: all
  "1.22.1":
    folder: all
  "1.22.0":
    folder: all
  "1.21.0":
    folder: all
  "1.20.1":
    folder: all
  "1.19.1":
    folder: all
  "1.19.0":
    folder: all
  "1.18.1":
    folder: all
