versions:
  "1.48.0":
    folder: all
  "1.48.1":
    folder: all
  "1.48.2":
    folder: all
  "1.48.3":
    folder: all
  "1.48.4":
    folder: all
  "1.48.5":
    folder: all
  "1.48.6":
    folder: all
  "1.48.7":
    folder: all
  "1.48.9":
    folder: all
  "1.49.0":
    folder: all
  "1.49.1":
    folder: all
  "1.49.2":
    folder: all
  "1.49.3":
    folder: all
