versions:
  "2.78.3":
    folder: all
  "2.78.1":
    folder: all
  "2.78.0":
    folder: all
  "2.77.3":
    folder: all
  "2.77.2":
    folder: all
  "2.77.1":
    folder: all
  "2.77.0":
    folder: all
  "2.76.3":
    folder: all
  "2.75.3":
    folder: all
