versions:
  "2.65.0":
    folder: all
  "2.65.1":
    folder: all
  "2.65.2":
    folder: all
  "2.65.3":
    folder: all
  "2.66.0":
    folder: all
  "2.66.1":
    folder: all
  "2.66.2":
    folder: all
  "2.67.0":
    folder: all
  "2.67.1":
    folder: all
