versions:
  "2.76.2":
    folder: all
  "2.76.1":
    folder: all
  "2.76.0":
    folder: all
  "2.75.3":
    folder: all
  "2.75.2":
    folder: all
  "2.75.1":
    folder: all
  "2.75.0":
    folder: all
  "2.74.1":
    folder: all
  "2.73.3":
    folder: all
  "2.72.4":
    folder: all
