versions:
  "3.3.2":
    folder: all
  "3.3.1":
    folder: all
  "3.3.0":
    folder: all
  "3.2.1":
    folder: all
  "3.2.0":
    folder: all
  "3.1.1":
    folder: all
  "2.5.0":
    folder: all
  "2.4.0":
    folder: all
