versions:
  "0.655":
    folder: all
  "0.650":
    folder: all
  "0.645":
    folder: all
  "0.640":
    folder: all
  "0.635":
    folder: all
  "0.630":
    folder: all
  "0.625":
    folder: all
  "0.620":
    folder: all
