versions:
  "0.572":
    folder: all
  "0.568":
    folder: all
  "0.563":
    folder: all
  "0.558":
    folder: all
  "0.556":
    folder: all
  "0.552":
    folder: all
  "0.548":
    folder: all
  "0.544":
    folder: all
  "0.541":
    folder: all
  "0.540":
    folder: all
