versions:
  "2021.5.0":
    folder: all
  "2021.3.0":
    folder: all
  "2020.3":
    folder: "2020.x"
  "2020.2":
    folder: "2020.x"
  "2020.1":
    folder: "2020.x"
  "2020.0":
    folder: "2020.x"
  "2019_u9":
    folder: "2020.x"
