versions:
  "1.59.0":
    folder: all
  "1.58.0":
    folder: all
  "1.57.0":
    folder: all
  "1.56.0":
    folder: all
  "1.55.1":
    folder: all
  "1.55.0":
    folder: all
  "1.54.0":
    folder: all
  "1.53.0":
    folder: all
  "1.51.0":
    folder: all
  "1.50.0":
    folder: all
