versions:
  "0.8.8":
    folder: all
  "0.8.7":
    folder: all
  "0.8.6":
    folder: all
  "0.8.5":
    folder: all
  "0.8.3":
    folder: all
  "0.8.2":
    folder: all
  "0.8.1":
    folder: all
  "0.7.1":
    folder: all
  "0.6.0":
    folder: all
  "0.4.0":
    folder: all
