versions:
  "48":
    folder: all
  "47":
    folder: all
  "46":
    folder: all
  "45":
    folder: all
  "43":
    folder: all
  "42":
    folder: all
  "41":
    folder: all
  "40":
    folder: all
  "39":
    folder: all
