versions:
  "2.2.1":
    folder: all
  "2.1.7":
    folder: all
  "2.1.6":
    folder: all
  "2.1.5":
    folder: all
  "2.1.4":
    folder: all
  "2.1.3":
    folder: all
  "2.1.2":
    folder: all
  "2.0.7":
    folder: all
  "2.0.6":
    folder: all
  "2.0.5":
    folder: all
  "2.0.2":
    folder: all
