versions:
  "5.6.1":
    folder: cmake
  "5.6.0":
    folder: cmake
  "5.4.5":
    folder: all
  "5.4.4":
    folder: all
  "5.4.2":
    folder: all
  "5.4.0":
    folder: all
  "5.2.10":
    folder: all
  "5.2.5":
    folder: all
  "5.2.4":
    folder: all
