versions:
  "2.11.1":
    folder: all
  "2.10.5":
    folder: all
  "2.10.2":
    folder: all
  "2.10.0":
    folder: all
  "2.8.0":
    folder: all
  "2.6.1":
    folder: all
  "2.6.0":
    folder: all
  "2.4.3":
    folder: all
