versions:
  "2.15.0":
    folder: all
  "2.14.4":
    folder: all
  "2.13.1":
    folder: all
  "2.13.0":
    folder: all
  "2.12.0":
    folder: all
  "2.11.3":
    folder: all
  "2.10.5":
    folder: all
