versions:
  "0.10.0":
    folder: all
  "0.9.5":
    folder: all
  "0.9.2":
    folder: all
  "0.8.8":
    folder: all
  "0.8.7":
    folder: all
  "0.8.0":
    folder: all
  "0.6.0":
    folder: all
  "0.5.5":
    folder: all
  "0.5.4":
    folder: all
  "0.5.2":
    folder: all
  "0.4.3":
    folder: all
