versions:
  "0.6.0":
    folder: all
  "0.5.5":
    folder: all
  "0.5.4":
    folder: all
  "0.5.2":
    folder: all
  "0.4.3":
    folder: all
  "0.3.3":
    folder: all
  "0.3.2":
    folder: all
  "0.3.1":
    folder: all
