versions:
  "1.3.0":
    folder: all
  "1.2.1":
    folder: all
  1.2.0:
    folder: all
  1.1.0:
    folder: all
  1.0.0:
    folder: all
  0.9.0:
    folder: all
  0.5.0:
    folder: all
  0.4.0:
    folder: all
  0.3.0:
    folder: all
  0.1.2:
    folder: all
  0.1.1:
    folder: all
  0.1.0:
    folder: all
