versions:
  "4.4.26":
    folder: all
  "4.4.25":
    folder: all
  "4.4.23":
    folder: all
  "4.4.22":
    folder: all
  "4.4.18":
    folder: all
  "4.4.17":
    folder: all
  "4.4.16":
    folder: all
