versions:
  "1.3.216.0":
    folder: all
  "1.3.211.0":
    folder: all
  "1.3.204.1":
    folder: all
  "1.2.198.0":
    folder: all
  "1.2.189.2":
    folder: all
  "1.2.182":
    folder: all
  "1.2.154.0":
    folder: all
