versions:
  "2.7":
    folder: all
  "2.6":
    folder: all
  "2.5":
    folder: all
  "2.4":
    folder: all
  "2.3":
    folder: all
  "2.2":
    folder: all
  "2.1":
    folder: all
  "2.0":
    folder: all
  "0.7":
    folder: all
