versions:
  "5.15.2":
    folder: 5.x.x
  "5.15.3":
    folder: 5.x.x
  "5.15.4":
    folder: 5.x.x
  "5.15.5":
    folder: 5.x.x
  "5.15.6":
    folder: 5.x.x
  "6.0.4":
    folder: 6.x.x
  "6.1.3":
    folder: 6.x.x
  "6.2.4":
    folder: 6.x.x
  "6.3.0":
    folder: 6.x.x
  "6.3.1":
    folder: 6.x.x
