versions:
  "20250814.0":
    folder: all
  "20250512.1":
    folder: all
  "20250127.0":
    folder: all
  "20240722.1":
    folder: all
  "20240722.0":
    folder: all
  "20240116.2":
    folder: all
  "20240116.1":
    folder: all
  "20230802.1":
    folder: all
  "20230125.3":
    folder: all
