versions:
  "20240722.0":
    folder: all
  "20240116.2":
    folder: all
  "20240116.1":
    folder: all
  "20230802.1":
    folder: all
  "20230125.3":
    folder: all
  "20220623.1":
    folder: all
  "20211102.0":
    folder: all
