versions:
  "4.4.0":
    folder: "all"
  "4.3.0":
    folder: "all"
  "4.2.1":
    folder: "all"
  "4.1.1":
    folder: "all"
  "4.1.0":
    folder: "all"
  "4.0.2":
    folder: "all"
  "4.0.1":
    folder: "all"
