versions:
  "5.4.0":
    folder: all
  "5.3.0":
    folder: all
  "5.2.0":
    folder: all
  "5.1.1":
    folder: all
  "5.0.0":
    folder: all
  "4.8.1":
    folder: all
  "4.7.1":
    folder: all
  "4.6.0":
    folder: all
  "4.5.0":
    folder: all
  "4.4.0":
    folder: all
