versions:
  "1.9.2":
    folder: all
  "1.9.1":
    folder: all
  "1.8.2":
    folder: all
  "1.8.0":
    folder: all
  "1.7.0":
    folder: all
  "1.6.1":
    folder: all
  "1.6.0":
    folder: all
  "1.5.3":
    folder: all
