versions:
  "1.3.0":
    folder: all
  "1.4.0":
    folder: all
  "1.5.2":
    folder: all
  "1.5.3":
    folder: all
  "1.6.0":
    folder: all
  "1.6.1":
    folder: all
  "1.7.0":
    folder: all
  "1.8.0":
    folder: all
  "1.8.2":
    folder: all
