versions:
  "1.3.8":
    folder: all
  "1.4.3":
    folder: all
  "1.4.4":
    folder: all
  "1.4.5":
    folder: all
  "1.4.7":
    folder: all
  "1.4.8":
    folder: all
  "1.4.9":
    folder: all
  "1.5.0":
    folder: all
  "1.5.1":
    folder: all
  "1.5.2":
    folder: all
