versions:
  "1.34.2":
    folder: all
  "1.38.0":
    folder: all
  "1.38.1":
    folder: all
  "1.40.0":
    folder: all
  "1.41.0":
    folder: all
  "1.41.1":
    folder: all
  "1.42.0":
    folder: all
  "1.43.0":
    folder: all
  "1.44.1":
    folder: all
