versions:
  "0.8.0":
    folder: all
  "0.7.3":
    folder: all
  "0.7.2":
    folder: all
  "0.7.1":
    folder: all
  "0.6.0":
    folder: all
  "0.5.0":
    folder: all
  "0.4.0":
    folder: all
  "0.3.4":
    folder: all
  "0.3.3":
    folder: all
  "0.2.66":
    folder: all
