versions:
  "4.1.1":
    folder: all
  "4.1.0":
    folder: all
  "4.0.0":
    folder: all
  "3.0.0":
    folder: all
  "2.1.2":
    folder: all
  "2.0.4":
    folder: all
  "1.3.0":
    folder: all
  "1.1.5":
    folder: all
  "1.0.0":
    folder: all
