versions:
  "1.8.1":
    folder: all
  "1.7.0":
    folder: all
  "1.6.1":
    folder: all
  "1.4.1":
    folder: all
  "1.4.0":
    folder: all
  "1.3.0":
    folder: all
  "1.2.0":
    folder: all
  "1.0.1":
    folder: all
