versions:
  "1.21.0":
    folder: all
  "1.18.0":
    folder: all
  "1.17.0":
    folder: all
  "1.16.1":
    folder: all
  "1.14.2":
    folder: all
  "1.12.0":
    folder: all
  "1.9.1":
    folder: all
  "1.8.3":
    folder: all
