versions:
  "3.46.1":
    folder: all
  "3.46.0":
    folder: all
  "3.45.3":
    folder: all
  "3.45.2":
    folder: all
  "3.45.1":
    folder: all
  "3.45.0":
    folder: all
  "3.44.2":
    folder: all
  "3.44.1":
    folder: all
  "3.44.0":
    folder: all
  "3.43.2":
    folder: all
  "3.43.1":
    folder: all
  "3.43.0":
    folder: all
  "3.42.0":
    folder: all
  "3.41.2":
    folder: all
  "3.41.1":
    folder: all
  "3.40.1":
    folder: all
  "3.40.0":
    folder: all
  "3.39.4":
    folder: all
  "3.39.3":
    folder: all
  "3.39.2":
    folder: all
  "3.39.1":
    folder: all
  "3.39.0":
    folder: all
  "3.38.5":
    folder: all
  "3.37.2":
    folder: all
  "3.36.0":
    folder: all
