versions:
  "3.39.2":
    folder: all
  "3.39.1":
    folder: all
  "3.39.0":
    folder: all
  "3.38.5":
    folder: all
  "3.38.4":
    folder: all
  "3.38.3":
    folder: all
  "3.38.1":
    folder: all
  "3.38.0":
    folder: all
  "3.37.2":
    folder: all
  "3.37.0":
    folder: all
  "3.36.0":
    folder: all
  "3.35.5":
    folder: all
