versions:
  "3.29.0":
    folder: all
  "3.30.1":
    folder: all
  "3.31.0":
    folder: all
  "3.31.1":
    folder: all
  "3.32.1":
    folder: all
  "3.32.2":
    folder: all
  "3.32.3":
    folder: all
  "3.33.0":
    folder: all
  "3.34.0":
    folder: all
  "3.34.1":
    folder: all
  "3.35.1":
    folder: all
  "3.35.2":
    folder: all
  "3.35.3":
    folder: all
  "3.35.4":
    folder: all
  "3.35.5":
    folder: all
  "3.36.0":
    folder: all
  "3.37.0":
    folder: all
  "3.37.1":
    folder: all
