versions:
  "0.24.2":
    folder: all
  "0.24.0":
    folder: all
  "0.23.10":
    folder: all
  "0.23.9":
    folder: all
  "0.21.5":
    folder: all
  "0.21.4":
    folder: all
  "0.21.3":
    folder: all
  "0.21.2":
    folder: all
