versions:
  "1.11.1":
    folder: all
  "1.10.3":
    folder: all
  "1.10.0":
    folder: all
  "1.9.2":
    folder: all
  "1.9.1":
    folder: all
  "1.9.0":
    folder: all
  "1.8.3":
    folder: all
  "1.8.2":
    folder: all
  "1.8.1":
    folder: all
  "1.8.0":
    folder: all
