versions:
  "64.2":
    folder: all
  "65.1":
    folder: all
  "66.1":
    folder: all
  "67.1":
    folder: all
  "68.2":
    folder: all
  "69.1":
    folder: all
  "70.1":
    folder: all
  "71.1":
    folder: all
