versions:
  "4.0.4":
    folder: all
  "4.0.1":
    folder: all
  "4.0.0":
    folder: all
  "3.2.5":
    folder: all
  "3.2.4":
    folder: all
  "3.2.3":
    folder: all
  "3.2.2":
    folder: all
  "3.2.1":
    folder: all
  "3.2":
    folder: all
  "3.1.2":
    folder: all
  "3.1.1":
    folder: all
  "3.1":
    folder: all
