versions:
  # Newer versions at the top
  "0.6.3":
    folder: all
  "0.6.2":
    folder: all
  "0.6.1":
    folder: all
  "0.6.0":
    folder: all
  "0.5.4":
    folder: all
  "0.5.3":
    folder: all
  "0.5.2":
    folder: all
  "0.5.1":
    folder: all
  "0.5.0":
    folder: all
  "0.4.1":
    folder: all
  "0.4.0":
    folder: all
  "0.3.1":
    folder: all
  "0.3.0":
    folder: all
  "0.2.1":
    folder: all
