versions:
  "0.7.1":
    folder: all
  "0.7.0":
    folder: all
  "0.6.3":
    folder: all
  "0.6.2":
    folder: all
  "0.6.1":
    folder: all
  "0.6.0":
    folder: all
  "0.3.1":
    folder: all
  "0.2.1":
    folder: all
