versions:
  "1.2.3":
    folder: all
  "1.3.0":
    folder: all
  "1.3.3":
    folder: all
  "2.0.0":
    folder: all
  "2.1.0":
    folder: all
  "2.2.0":
    folder: all
  "2.3.0":
    folder: all
  "2.4.0":
    folder: all
  "2.5.0":
    folder: all
  "3.0.1":
    folder: all
  "3.1.0":
    folder: all
  "3.2.0":
    folder: all
