versions:
  "3.18.00":
    folder: "all"
  "3.17.06":
    folder: "all"
  "3.17.03":
    folder: "all"
  "3.16.07":
    folder: "all"
  "3.16.05":
    folder: "all"
  "3.16.01":
    folder: "all"
  "3.15.00":
    folder: "all"
