versions:
  "2022.05.18":
    folder: all
  "2022.01.04":
    folder: all
  "2021.06.30":
    folder: all
  "2021.04.29":
    folder: all
  "2020.12.18":
    folder: all
  "2020.06.16":
    folder: all
  "2020.03.13":
    folder: all
