versions:
  "1.1.3":
    folder: "all"
  "1.1.2":
    folder: "all"
  "1.1.1":
    folder: "all"
  "1.1.0":
    folder: "all"
  "1.0.0":
    folder: "all"
  "0.10.2":
    folder: "all"
  "0.10.1":
    folder: "all"
  "0.9.2":
    folder: "all"
