versions:
  "1.3.224.0":
    folder: all
  "1.3.216.0":
    folder: all
  "1.3.211.0":
    folder: all
  "1.3.204.0":
    folder: all
  "11.7.0":
    folder: all
  "11.6.0":
    folder: all
  "11.5.0":
    folder: all
  "8.13.3559":
    folder: all
