versions:
  "0.6.8":
    folder: all
  "0.6.8.1":
    folder: all
  "0.6.9":
    folder: all
  "0.6.10":
    folder: all
  "0.6.11":
    folder: all
  "0.6.12":
    folder: all
  "0.6.13":
    folder: all
  "0.6.14":
    folder: all
  "0.6.15":
    folder: all
  "0.6.16":
    folder: all
  "0.6.17":
    folder: all
