versions:
  "0.51.2":
    folder: all
  "0.52.0":
    folder: all
  "0.52.1":
    folder: all
  "0.53.0":
    folder: all
  "0.53.1":
    folder: all
  "0.53.2":
    folder: all
  "0.54.0":
    folder: all
