versions:
  "1.4.0":
    folder: all
  "1.3.2":
    folder: all
  "1.3.1":
    folder: all
  "1.3.0":
    folder: all
  "1.2.3":
    folder: all
  "1.2.2":
    folder: all
  "1.2.1":
    folder: all
  "1.2.0":
    folder: all
  "1.1.1":
    folder: all
  "1.1.0":
    folder: all
  "1.0.1":
    folder: all
  "1.0.0":
    folder: all
  "0.64.1":
    folder: all
  "0.64.0":
    folder: all
  "0.63.3":
    folder: all
  "0.63.2":
    folder: all
  "0.63.1":
    folder: all
  "0.63.0":
    folder: all
  "0.62.2":
    folder: all
  "0.62.1":
    folder: all
  "0.62.0":
    folder: all
  "0.61.2":
    folder: all
  "0.60.2":
    folder: all
  "0.59.3":
    folder: all
  "0.58.1":
    folder: all
  "0.57.2":
    folder: all
  "0.56.2":
    folder: all
  "0.55.3":
    folder: all
