versions:
  # "0.51.0":
  #   folder: all
  "0.51.2":
    folder: all
  # "0.52.0":
  #   folder: all
  "0.52.1":
    folder: all
  # "0.53.0":
  #   folder: all
  # "0.53.1":
  #   folder: all
  "0.53.2":
    folder: all
  # "0.54.0":
  #   folder: all
  # "0.54.1":
  #   folder: all
  # "0.54.2":
  #   folder: all
  "0.54.3":
    folder: all
  # "0.55.0":
  #   folder: all
  # "0.55.1":
  #   folder: all
  # "0.55.2":
  #   folder: all
  "0.55.3":
    folder: all
  # "0.56.0":
  #   folder: all
  # "0.56.1":
  #   folder: all
  "0.56.2":
    folder: all
  # "0.57.0":
  #   folder: all
  # "0.57.1":
  #   folder: all
  "0.57.2":
    folder: all
  # "0.58.0":
  #   folder: all
  "0.58.1":
    folder: all
  # "0.59.0":
  #   folder: all
  # "0.59.1":
  #   folder: all
  # "0.59.2":
  #   folder: all
  "0.59.3":
    folder: all
  "0.60.2":
    folder: all
  "0.61.2":
    folder: all
  "0.62.0":
    folder: all
  "0.62.1":
    folder: all
  "0.62.2":
    folder: all
  "0.63.0":
    folder: all
  "0.63.1":
    folder: all
