versions:
  "1.9.1":
    folder: all
  "1.8.2":
    folder: all
  "1.7.2":
    folder: all
  "1.6.0":
    folder: all
  "1.5.1":
    folder: all
  "1.4.1":
    folder: all
  "1.3.2":
    folder: all
  "1.2.3":
    folder: all
  "1.1.1":
    folder: all
  "1.0.0":
    folder: all
  "0.62.2":
    folder: all
  "0.61.2":
    folder: all
  "0.59.3":
    folder: all
