versions:
  "2.4.2":
    folder: all
  "2.4.1":
    folder: all
  "2.4.0":
    folder: all
  "2.3.2":
    folder: all
  "2.3.1":
    folder: all
  "2.3.0":
    folder: all
  "2.2.0":
    folder: all
  "2.1.2":
    folder: all
  "2.1.1":
    folder: all
  "2.0.0":
    folder: all
  "1.9.1":
    folder: all
