versions:
  "1.29.2":
    folder: "all"
  "1.29.1":
    folder: "all"
  "1.28.0":
    folder: "all"
  "1.27.0":
    folder: "all"
  "1.26.0":
    folder: "all"
  "1.25.0":
    folder: "all"
  "1.24.0":
    folder: "all"
  "1.23.0":
    folder: "all"
