versions:
  "1.3.224.0":
    folder: all
  "1.3.216.0":
    folder: all
  "1.3.211.0":
    folder: all
  "1.3.204.0":
    folder: all
  "1.2.198.0":
    folder: all
  "cci.20211010":
    folder: all
  "cci.20210811":
    folder: all
  "cci.20210616":
    folder: all
  "cci.20210414":
    folder: all
  "1.5.4":
    folder: all
  "1.5.3":
    folder: all
  "1.5.1":
    folder: all
