versions:
  "8.9.1":
    folder: all
  "8.8.0":
    folder: all
  "8.6.0":
    folder: all
  "8.5.0":
    folder: all
  "8.4.0":
    folder: all
  "8.2.1":
    folder: all
  "8.1.2":
    folder: all
  "8.0.1":
    folder: all
  "7.88.1":
    folder: all
