versions:
  "7.85.0":
    folder: all
  "7.84.0":
    folder: all
  "7.83.1":
    folder: all
  "7.82.0":
    folder: all
  "7.80.0":
    folder: all
  "7.79.1":
    folder: all
  "7.78.0":
    folder: all
  "7.77.0":
    folder: all
  "7.76.0":
    folder: all
