versions:
  "7.79.1":
    folder: all
  "7.79.0":
    folder: all
  "7.78.0":
    folder: all
  "7.77.0":
    folder: all
  "7.76.0":
    folder: all
  "7.75.0":
    folder: all
  "7.74.0":
    folder: all
  "7.73.0":
    folder: all
  "7.72.0":
    folder: all
  "7.71.1":
    folder: all
  "7.71.0":
    folder: all
  "7.70.0":
    folder: all
  "7.69.1":
    folder: all
  "7.68.0":
    folder: all
  "7.67.0":
    folder: all
  "7.66.0":
    folder: all
  "7.64.1":
    folder: all
