versions:
  "2.1.2":
    folder: all
  "2.0.2":
    folder: all
  "1.30.3":
    folder: 1.x
  "1.29.2":
    folder: 1.x
  "1.29.1":
    folder: 1.x
  "1.29.0":
    folder: 1.x
  "1.28.1":
    folder: 1.x
  "1.27.6":
    folder: 1.x
  "1.26.2":
    folder: 1.x
  "1.24.3":
    folder: 1.x
