versions:
  "1.27.5":
    folder: all
  "1.27.4":
    folder: all
  "1.27.3":
    folder: all
  "1.27.2":
    folder: all
  "1.27.1":
    folder: all
  "1.26.2":
    folder: all
  "1.24.3":
    folder: all
  "1.23.5":
    folder: all
