versions:
  "4.0.0":
    folder: all
  "3.2.11":
    folder: all
  "3.2.8":
    folder: all
  "3.2.4":
    folder: all
  "3.1.4":
    folder: all
  "3.1.3":
    folder: all
  "3.1.2":
    folder: all
  "3.1.1":
    folder: all
  "3.1.0":
    folder: all
  "3.0.4":
    folder: all
  "3.0.1":
    folder: all
  "2.4.8":
    folder: all
  "2.4.7":
    folder: all
  "2.4.6":
    folder: all
  "2.3.2":
    folder: all
