versions:
  "0.9.12":
    folder: all
  "0.9.6":
    folder: all
  "0.9.3":
    folder: all
  "0.9.0":
    folder: all
  "0.8.23":
    folder: all
  "0.8.2":
    folder: all
  "0.7.5":
    folder: all
  "0.6.20":
    folder: all
  "0.4.25":
    folder: all
