versions:
  "4.8.0":
    folder: all
  "4.7.1":
    folder: all
  "4.6.2":
    folder: all
  "4.6.0":
    folder: all
  "4.5.1":
    folder: all
  "4.5.0":
    folder: all
  "4.4.0":
    folder: all
  "4.3.1":
    folder: all
