versions:
  "4.10.0":
    folder: "4.x"
  "4.9.0":
    folder: "4.x"
  "4.8.1":
    folder: "4.x"
  "4.5.5":
    folder: "4.x"
  "4.5.3":
    folder: "4.x"
  "4.1.2":
    folder: "4.x"
  "3.4.20":
    folder: "3.x"
  "3.4.17":
    folder: "3.x"
  "2.4.13.7":
    folder: "2.x"
