versions:
  "1.3.216.0":
    folder: "all"
  "1.3.204":
    folder: "all"
  "1.2.198":
    folder: "all"
  "1.2.195":
    folder: "all"
  "1.2.190":
    folder: "all"
  "1.2.182":
    folder: "all"
  "1.2.170":
    folder: "all"
  "1.2.162":
    folder: "all"
  "1.2.140":
    folder: "all"
