versions:
  "14.2":
    folder: all
  "13.6":
    folder: all
  "13.4":
    folder: all
  "13.3":
    folder: all
  "13.2":
    folder: all
  "12.10":
    folder: all
  "12.2":
    folder: all
  "11.15":
    folder: all
  "11.9":
    folder: all
  "10.20":
    folder: all
  "9.6.24":
    folder: all
