versions:
  "1.0.240803.1":
    folder: "all"
  "1.0.240122.1":
    folder: "all"
  "1.0.231216.1":
    folder: "all"
  "1.0.231028.1":
    folder: "all"
  "1.0.230824.2":
    folder: "all"
  "1.0.230629.1":
    folder: "all"
  "1.0.230411.1":
    folder: "all"
  "1.0.230202.1":
    folder: "all"
