versions:
  "7.7.5":
    folder: all
  "7.7.4":
    folder: all
  "7.7.3":
    folder: all
  "7.7.2":
    folder: all
  "7.7.0":
    folder: all
  "7.6.1":
    folder: all
  "7.6.0":
    folder: all
  "7.5.3":
    folder: all
  "7.4.2":
    folder: all
  "7.3.2":
    folder: all
  "7.2.1":
    folder: all
  "7.1.2":
    folder: all
  "7.0.7":
    folder: all
  "6.4.8":
    folder: all
