versions:
  "0.27.0":
    folder: all
  "0.20.1":
    folder: all
  "0.19.0":
    folder: all
  "0.18.3":
    folder: all
  "0.17.3":
    folder: all
  "0.16.3":
    folder: all
  "0.15.3":
    folder: all
  "0.14.3":
    folder: all
  "0.14.1":
    folder: all
