versions:
  "0.15.3":
    folder: all
  "0.15.2":
    folder: all
  "0.15.1":
    folder: all
  "0.14.3":
    folder: all
  "0.14.2":
    folder: all
  "0.14.1":
    folder: all
  "0.14.0":
    folder: all
  "0.13.3":
    folder: all
  "0.13.1":
    folder: all
  "0.12.6":
    folder: all
  "0.11.4":
    folder: all
  "0.10.9":
    folder: all
