versions:
  "0.9.7":
    folder: all
  "0.9.5":
    folder: all
  "0.9.4":
    folder: all
  "0.9.3":
    folder: all
  "0.9.2":
    folder: all
  "0.9.0":
    folder: all
  "0.8.9":
    folder: all
  "0.8.8":
    folder: all
  "0.8.6":
    folder: all
  "0.8.5":
    folder: all
  "0.8.4":
    folder: all
  "0.8.0":
    folder: all
  "0.7.18":
    folder: all
  "0.7.15":
    folder: all
  "0.7.12":
    folder: all
  "0.7.10":
    folder: all
  "0.7.9":
    folder: all
  "0.7.8":
    folder: all
  "0.7.7":
    folder: all
  "0.7.6":
    folder: all
  "0.7.5":
    folder: all
  "0.7.0":
    folder: all
  "0.6.6":
    folder: all
  "0.5.13":
    folder: all
  "0.5.8":
    folder: all
  "0.5.7":
    folder: all
  "0.5.4":
    folder: all
