versions:
  "0.12.4":
    folder: all
  "0.12.3":
    folder: all
  "0.12.2":
    folder: all
  "0.12.1":
    folder: all
  "0.12.0":
    folder: all
  "0.11.4":
    folder: all
  "0.11.3":
    folder: all
  "0.11.2":
    folder: all
  "0.11.1":
    folder: all
  "0.11.0":
    folder: all
  "0.10.9":
    folder: all
  "0.9.10":
    folder: all
  "0.8.9":
    folder: all
  "0.7.18":
    folder: all
  "0.6.6":
    folder: all
