versions:
  "0.11.1":
    folder: all
  "0.11.0":
    folder: all
  "0.10.9":
    folder: all
  "0.10.8":
    folder: all
  "0.10.7":
    folder: all
  "0.10.6":
    folder: all
  "0.10.4":
    folder: all
  "0.10.3":
    folder: all
  "0.10.1":
    folder: all
  "0.9.10":
    folder: all
  "0.8.9":
    folder: all
  "0.7.18":
    folder: all
  "0.6.6":
    folder: all
  "0.5.13":
    folder: all
