versions:
  8.0.0:
    folder: all
  8.1.0:
    folder: all
  8.1.1:
    folder: all
  8.2.0:
    folder: all
  8.3.0:
    folder: all
  8.4.0:
    folder: all
  8.5.0:
    folder: all
  8.6.0:
    folder: all
