versions:
  "0.4.12":
    folder: all
  "0.4.11":
    folder: all
  "0.4.10":
    folder: all
  "0.4.9":
    folder: all
  "0.4.8":
    folder: all
  "0.4.7":
    folder: all
  "0.4.1":
    folder: all
  "0.2.6":
    folder: all
