versions:
  "2.11.1":
    folder: all
  "2.10.4":
    folder: all
  "2.10.3":
    folder: all
  "2.9.14":
    folder: all
  "2.9.13":
    folder: all
  "2.9.12":
    folder: all
  "2.9.10":
    folder: all
  "2.9.9":
    folder: all
