versions:
  "2.13.8":
    folder: all
  "2.13.6":
    folder: all
  "2.13.4":
    folder: all
  "2.12.9":
    folder: all
  "2.12.4":
    folder: all
  "2.12.3":
    folder: all
  "2.11.9":
    folder: all
  "2.11.6":
    folder: all
  "2.11.4":
    folder: all
  "2.10.4":
    folder: all
  "2.10.3":
    folder: all
  "2.9.14":
    folder: all
  "2.9.12":
    folder: all
  "2.9.10":
    folder: all
