versions:
  "5.0":
    folder: all
  "5.0.1":
    folder: all
  "5.0.2":
    folder: all
  "5.0.3":
    folder: all
  "5.1":
    folder: all
  "5.1.1":
    folder: all
  "5.1.3":
    folder: all
  "5.2":
    folder: all
  "5.2.1":
    folder: all
  "5.3":
    folder: all
  "5.5":
    folder: all
