versions:
  "3.2.6":
    folder: 3.x
  "2.32.2":
    folder: all
  "2.30.9":
    folder: all
  "2.30.8":
    folder: all
  "2.30.7":
    folder: all
  "2.30.6":
    folder: all
  # keep 2.30.5 for sdl_mixer
  "2.30.5":
    folder: all
  "2.30.4":
    folder: all
  # keep 2.28.5 for pdcurses, ffmpeg, sdl_net, sdl_mixer
  "2.28.5":
    folder: all
  # keep 2.28.3 for sdl_image, sdl_ttf
  "2.28.3":
    folder: all
  # keep 2.0.20 for magnum, ogre
  "2.0.20":
    folder: all
