versions:
  "2.30.6":
    folder: all
  "2.30.5":
    folder: all
  "2.30.4":
    folder: all
  "2.30.3":
    folder: all
  "2.30.2":
    folder: all
  "2.30.1":
    folder: all
  "2.28.5":
    folder: all
  "2.28.3":
    folder: all
  "2.28.2":
    folder: all
  "2.26.5":
    folder: all
  "2.26.1":
    folder: all
  "2.26.0":
    folder: all
  "2.24.1":
    folder: all
  "2.24.0":
    folder: all
  "2.0.20":
    folder: all
