versions:
  "2.73":
    folder: all
  "2.70":
    folder: all
  "2.69":
    folder: all
  "2.68":
    folder: all
  "2.66":
    folder: all
  "2.65":
    folder: all
  "2.62":
    folder: all
  "2.58":
    folder: all
  "2.57":
    folder: all
  "2.50":
    folder: all
  "2.48":
    folder: all
  "2.46":
    folder: all
  "2.45":
    folder: all
