versions:
  "2.45":
    folder: all
  "2.46":
    folder: all
  "2.48":
    folder: all
  "2.50":
    folder: all
  "2.57":
    folder: all
  "2.58":
    folder: all
  "2.62":
    folder: all
  "2.65":
    folder: all
