versions:
  "253.10":
    folder: all
  "253.6":
    folder: all
  "253.3":
    folder: all
  "252.9":
    folder: all
  "251.15":
    folder: all
  "249.16":
    folder: all
  "248.12":
    folder: all
  "247.13":
    folder: all
  "246.16":
    folder: all
