versions:
  "1.5.0":
    folder: all
  "1.4.16":
    folder: all
  "1.4.13":
    folder: all
  "1.4.1":
    folder: all
  "1.4.0":
    folder: all
  "1.3.56":
    folder: all
  "1.3.55":
    folder: all
  "1.3.52":
    folder: all
  "1.3.50":
    folder: all
  "1.3.49":
    folder: all
  "1.3.31":
    folder: all
  "1.3.15":
    folder: all
  "1.3.9":
    folder: all
  "1.2.0":
    folder: all
  "1.1.1":
    folder: all
  "1.1.0":
    folder: all
  "1.0.11":
    folder: all
