versions:
  "1.5.9":
    folder: all
  "1.5.7":
    folder: all
  "1.5.6":
    folder: all
  "1.5.5":
    folder: all
  "1.5.3":
    folder: all
  "1.5.2":
    folder: all
  "1.5.1":
    folder: all
  "1.5.0":
    folder: all
  # keep 1.4.16 for aws-sdk-cpp, aws-c-io
  "1.4.16":
    folder: all
  # keep 1.3.15 for aws-sdk-cpp, aws-c-io
  "1.3.15":
    folder: all
