versions:
  "0.7.4":
    folder: all
  "0.7.3":
    folder: all
  "0.7.2":
    folder: all
  "0.6.21":
    folder: all
  "0.6.12":
    folder: all
  "0.6.11":
    folder: all
  "0.6.10":
    folder: all
  "0.6.9":
    folder: all
