versions:
  "2.4.9":
    folder: all
  "2.4.8":
    folder: all
  "2.4.7":
    folder: all
  "2.4.6":
    folder: all
  "2.4.5":
    folder: all
  "2.4.4":
    folder: all
  "2.4.3":
    folder: all
  "2.4.2":
    folder: all
  "2.4.1":
    folder: all
  "2.3.0":
    folder: all
  "2.2.10":
    folder: all
  "2.2.9":
    folder: all
  "2.2.8":
    folder: all
  "2.2.7":
    folder: all
