versions:
  "1.13.1":
    folder: all
  "1.12.2":
    folder: all
  "1.12.1":
    folder: all
  "1.12.0":
    folder: all
  "1.10.6":
    folder: all
  "1.10.5":
    folder: all
  "1.8.21":
    folder: all
