versions:
  "0.10.6":
    folder: all
  "0.10.5":
    folder: all
  "0.10.4":
    folder: all
  "0.10":
    folder: all
  "0.9":
    folder: all
  "0.8":
    folder: all
  "0.0.18":
    folder: all
  "0.0.17":
    folder: all
