versions:
  "0.11.4":
    folder: all
  "0.11.3":
    folder: all
  "0.11.1":
    folder: all
  "0.10.6":
    folder: all
  "0.10.5":
    folder: all
  "0.10.4":
    folder: all
  "0.10":
    folder: all
  "0.9":
    folder: all
  "0.8":
    folder: all
