versions:
  "2024.3.0":
    folder: "all"
  "2024.2.0":
    folder: "all"
  "2024.1.0":
    folder: "all"
  "2024.0.0":
    folder: "all"
  "2023.3.0":
    folder: "all"
  "2023.2.0":
    folder: "all"
