versions:
  "1.1.0":
    folder: all
  "1.0.0":
    folder: all
  "0.20.0":
    folder: all
  "0.19.0":
    folder: all
  "0.18.0":
    folder: all
  "0.17.0":
    folder: all
  "0.16.0":
    folder: all
  "0.11.0":
    folder: all
