versions:
  "5.3.0":
    folder: all
  "6.0.0":
    folder: all
  "6.1.0":
    folder: all
  "6.1.1":
    folder: all
  "6.1.2":
    folder: all
  "6.2.0":
    folder: all
  "6.2.1":
    folder: all
  "7.0.1":
    folder: all
  "7.0.2":
    folder: all
  "7.0.3":
    folder: all
  "7.1.0":
    folder: all
  "7.1.1":
    folder: all
  "7.1.2":
    folder: all
  "7.1.3":
    folder: all
  "8.0.0":
    folder: all
  "8.0.1":
    folder: all
