versions:
  "1.18.2":
    folder: all
  "1.18.1":
    folder: all
  "1.18.0":
    folder: all
  "1.17.0":
    folder: all
  "1.16.1":
    folder: all
  "1.16.0":
    folder: all
  "1.14.1":
    folder: all
  "1.14.0":
    folder: all
  "1.13.0":
    folder: all
  "1.12.2":
    folder: all
