versions:
  "3.2.1":
    folder: all
  "3.1.0":
    folder: all
  "3.0.0":
    folder: all
  "2.25.0":
    folder: all
  "2.24.0":
    folder: all
  "2.23.0":
    folder: all
  "2.16.3-apache":
    folder: all
  "2.16.3-gpl":
    folder: all
