versions:
  "20.37.1":
    folder: all
  "20.37.0":
    folder: all
  "20.36.0":
    folder: all
  "20.35.14":
    folder: all
  "20.35.11":
    folder: all
  "20.35.8":
    folder: all
  "20.35.7":
    folder: all
  "20.34.0":
    folder: all
  "20.33.0":
    folder: all
  "20.32.1":
    folder: all
