versions:
  "20.33.0":
    folder: all
  "20.32.1":
    folder: all
  "20.31.3":
    folder: all
  "20.31.1":
    folder: all
  "20.31.0":
    folder: all
  "20.30.1":
    folder: all
  "20.29.3":
    folder: all
  "20.29.1":
    folder: all
  "20.28.0":
    folder: all
  "20.27.1":
    folder: all
  "20.25.0":
    folder: all
  "20.24.1":
    folder: all
