versions:
  "12.0.0":
    folder: all
  "11.0.0":
    folder: all
  "10.0.1":
    folder: all
  "10.0.0":
    folder: all
  "8.0.1":
    folder: all
  "8.0.0":
    folder: all
  "7.0.0":
    folder: all
  "2.0.0":
    folder: all
  "1.0.0":
    folder: all
