versions:
  "1.2.190":
    folder: all
  "1.2.189":
    folder: all
  "1.2.182":
    folder: all
  "1.2.172":
    folder: all
  "1.2.170.0":
    folder: all
  "1.2.162.0":
    folder: all
  "1.2.154.0":
    folder: all
