versions:
  "1.3.221":
    folder: all
  "1.3.216.0":
    folder: all
  "1.3.211.0":
    folder: all
  "1.3.204.1":
    folder: all
  "1.3.204.0":
    folder: all
  "1.2.198.0":
    folder: all
  "1.2.190":
    folder: all
  "1.2.189":
    folder: all
  "1.2.182":
    folder: all
  "1.2.172":
    folder: all
  "1.2.170.0":
    folder: all
  "1.2.162.0":
    folder: all
  "1.2.154.0":
    folder: all
