versions:
  "1.8.0":
    folder: "1.x.x"
  "1.6.1":
    folder: "1.x.x"
  "1.6.0":
    folder: "1.x.x"
  "1.5.0":
    folder: "1.x.x"
  "1.4.2":
    folder: "1.x.x"
  "1.4.1":
    folder: "1.x.x"
  "1.3.10":
    folder: "1.x.x"
  "1.3.9":
    folder: "1.x.x"
  "1.3.8":
    folder: "1.x.x"
  "0.1.13":
    folder: "0.x.x"
