versions:
  "3.8.1":
    folder: all
  "3.8.0":
    folder: all
  "3.7.1":
    folder: all
  "3.7.0":
    folder: all
  "3.6.1":
    folder: all
  "3.6.0":
    folder: all
  "3.5.0":
    folder: all
  "3.4.0":
    folder: all
  "3.1.0":
    folder: all
