versions:
  "3.5.1":
    folder: all
  "3.4.0":
    folder: all
  "3.2.0":
    folder: all
  "3.1.0":
    folder: all
  "2.0.0":
    folder: all
  "1.1.2":
    folder: all
  "1.1.1":
    folder: all
  "1.0.0":
    folder: all
  "0.9.0":
    folder: all
  "0.8.0":
    folder: all
