versions:
  "v14":
    folder: all
  "v13":
    folder: all
  "v12":
    folder: all
  "v11":
    folder: all
  "v10":
    folder: all
  "v9":
    folder: all
  "v8":
    folder: all
  "v7":
    folder: all
