versions:
  "2024.07.03":
    folder: all
  "2023.03.07":
    folder: all
  "2023.01.05":
    folder: all
  "2022.12.07":
    folder: all
  "2022.10.12":
    folder: all
  "2022.08.01":
    folder: all
  "2022.06.15":
    folder: all
