versions:
  "1.3.10":
    folder: all
  "1.3.9":
    folder: all
  "1.3.8":
    folder: all
  "1.3.6":
    folder: all
  "1.3.4":
    folder: all
  "1.3.3":
    folder: all
  "1.3.2":
    folder: all
  "1.2.0":
    folder: all
  "1.1.6":
    folder: all
  "1.1.5":
    folder: all
  "1.1.3":
    folder: all
  "1.1.2":
    folder: all
