versions:
  "1.5.4":
    folder: all
  "1.5.3":
    folder: all
  "1.5.0":
    folder: all
  "1.4.0":
    folder: all
  "1.3.10":
    folder: all
  "1.2.0":
    folder: all
  "1.1.6":
    folder: all
