versions:
  "7.9.2":
    folder: all
  "9.1.9":
    folder: all
  "9.6.4":
    folder: all
  "10.2.5":
    folder: all
  "10.4.0":
    folder: all
  "11.0.4":
    folder: all
  "11.0.9":
    folder: all
  "11.2.4":
    folder: all
  "11.4.3":
    folder: all
