versions:
  "6.21.0":
    folder: all
  "6.20.1":
    folder: all
  "6.19.4":
    folder: all
  "6.18.5":
    folder: all
  "6.18.0":
    folder: all
  "6.16.1":
    folder: all
  "6.15.2":
    folder: all
