versions:
  "4.0.3":
    folder: all
  "3.2.17":
    folder: all
  "3.2.15":
    folder: all
  "3.2.14":
    folder: all
  "3.2.2":
    folder: all
  "3.2.0":
    folder: all
  "3.1.0":
    folder: all
  "3.0.0":
    folder: all
  "2.2.0":
    folder: all
