versions:
  "5.6.3":
    folder: all
  "5.6.2":
    folder: all
  "5.6.0":
    folder: all
  "5.5.0":
    folder: all
  "5.4.15":
    folder: all
  "5.3.7":
    folder: all
  "5.3.5":
    folder: all
  "5.3.2":
    folder: all
  "5.3.1":
    folder: all
  "4.0.5":
    folder: all
