versions:
  "3.5.3":
    folder: all
  "3.5.2":
    folder: all
  "3.5.1":
    folder: all
  "3.4.4":
    folder: all
  "3.4":
    folder: all
  "3.3.4":
    folder: all
  "3.3.2":
    folder: all
  "3.2.3":
    folder: all
  "cci.3.2-20200130":
    folder: all
