versions:
  "1.0.1":
    folder: all
  "0.39.1":
    folder: all
  "0.38.0":
    folder: all
  "0.37.0":
    folder: all
  "0.36.0":
    folder: all
  "0.35.1":
    folder: all
  "0.34.0":
    folder: all
  "0.32.0":
    folder: all
