versions:
  "21.0.0":
    folder: all
  "20.0.1":
    folder: all
  "19.0.2":
    folder: all
  "18.0.3":
    folder: all
  "16.0.0":
    folder: all
  "12.0.2":
    folder: all
  "9.0.1":
    folder: all
  "7.0.0":
    folder: all
  "6.0.1":
    folder: all
