versions:
  "8.0.0":
    folder: all
  "7.0.0":
    folder: all
  "6.0.1":
    folder: all
  "5.0.0":
    folder: all
  "4.0.0":
    folder: all
  "3.0.0":
    folder: all
  "2.0.0":
    folder: all
  "1.0.1":
    folder: all
  "0.39.1":
    folder: all
  "0.38.0":
    folder: all
  "0.37.0":
    folder: all
  "0.36.0":
    folder: all
  "0.35.1":
    folder: all
