versions:
  "4.0.6":
    folder: all
  "4.0.5":
    folder: all
  "4.0.4":
    folder: all
  "4.0.3":
    folder: all
  "4.0.2":
    folder: all
  "4.0.1":
    folder: all
  "4.0.0":
    folder: all
  "3.0.10":
    folder: all
  "3.0.9":
    folder: all
  "3.0.8":
    folder: all
  "3.0.7":
    folder: all
