versions:
  "3.21.4":
    folder: all
  "3.21.1":
    folder: all
  "3.20.0":
    folder: all
  "3.19.4":
    folder: all
  "3.19.2":
    folder: all
  "3.18.1":
    folder: all
  "3.17.1":
    folder: all
  "3.16.0":
    folder: all
  "3.15.8":
    folder: all
  "3.15.5":
    folder: all
  "3.13.0":
    folder: all
  "3.12.4":
    folder: all
  "3.11.4":
    folder: all
  "3.9.1":
    folder: all
