versions:
  "6.32.1":
    folder: all
  "6.30.1":
    folder: all
  "5.29.3":
    folder: all
  "5.28.3":
    folder: all
  "5.27.0":
    folder: all
  "4.25.3":
    folder: all
  "3.21.12":
    folder: all
  "3.20.3":
    folder: all
