versions:
  "4.23.1":
    folder: all
  "4.22.0":
    folder: all
  "3.21.9":
    folder: all
  "3.21.4":
    folder: all
  "3.20.0":
    folder: all
  "3.19.6":
    folder: all
  "3.19.4":
    folder: all
  "3.18.1":
    folder: all
  "3.17.1":
    folder: all
