versions:
  "3.9.1":
    folder: all
  "3.11.3":
    folder: all
  "3.11.4":
    folder: all
  "3.12.4":
    folder: all
  "3.13.0":
    folder: all
  "3.15.5":
    folder: all
  "3.16.0":
    folder: all
  "3.17.1":
    folder: all
