versions:
  "6.3.2":
    folder: all
  "6.3.1":
    folder: all
  "6.3.0":
    folder: all
  "6.2.0.1":
    folder: all
  "6.2.0.0":
    folder: all
  "6.1.1.0":
    folder: all
  "6.1.0.0":
    folder: all
  "6.0.1.0":
    folder: all
