versions:
  "62":
    folder: "all"
  "60":
    folder: "all"
  "58":
    folder: "all"
  "57":
    folder: "all"
  "56":
    folder: "all"
  "55":
    folder: "all"
  "52":
    folder: "all"
  "51":
    folder: "all"
