versions:
  "7.17.0":
    folder: all
  "7.16.0":
    folder: all
  "7.15.0":
    folder: all
  "7.12.0":
    folder: all
  "7.11.0":
    folder: all
  "7.8.0":
    folder: all
  "7.5.0":
    folder: all
  "7.4.0":
    folder: all
  "6.6.0":
    folder: all
