versions:
  "1.91.0":
    folder: all
  "1.91.0-docking":
    folder: all
  "1.90.9":
    folder: all
  "1.90.9-docking":
    folder: all
  "1.90.8":
    folder: all
  "1.90.8-docking":
    folder: all
  "1.90.7":
    folder: all
  "1.90.7-docking":
    folder: all
  "1.90.6":
    folder: all
  "1.90.6-docking":
    folder: all
  "1.90.5":
    folder: all
  "1.90.5-docking":
    folder: all
  "1.89.9":
    folder: all
  "1.89.9-docking":
    folder: all
  "1.88":
    folder: all
  "1.87":
    folder: all
  "1.86":
    folder: all
  "1.85":
    folder: all

