versions:
  "1.90.4":
    folder: all
  "1.90.4-docking":
    folder: all
  "1.90.3":
    folder: all
  "1.90.3-docking":
    folder: all
  "1.90.2":
    folder: all
  "1.90.2-docking":
    folder: all
  "1.90.1":
    folder: all
  "1.90.1-docking":
    folder: all
  "1.90":
    folder: all
  "1.90-docking":
    folder: all
  "1.89.9":
    folder: all
  "1.89.9-docking":
    folder: all
  "1.89.8":
    folder: all
  "1.89.8-docking":
    folder: all
  "1.89.7":
    folder: all
  "1.89.7-docking":
    folder: all
  "1.89.5":
    folder: all
  "1.89.4":
    folder: all
  "1.89.3":
    folder: all
  "1.89.2":
    folder: all
  "1.89.1":
    folder: all
  "1.88":
    folder: all
  "1.87":
    folder: all
  "1.86":
    folder: all
  "1.85":
    folder: all

  # These versions belong to the docking branch in ImGUI repository. This branch is declared stable and production ready, and
  # it is synced with `master` regularly. These versions are taken from that branch using the commit where `master` was synced
  # after a regular release
  "cci.20230105+1.89.2.docking":
    folder: all
  "cci.20220621+1.88.docking":
    folder: all
  "cci.20220207+1.87.docking":
    folder: all
