versions:
  "7.0.1":
    folder: "all"
  "6.1.1":
    folder: "all"
  "6.1":
    folder: "all"
  "6.0.1":
    folder: "all"
  "5.1.3":
    folder: "all"
  "5.0.3":
    folder: "all"
  "4.4.4":
    folder: "all"
