versions:
  "6.1":
    folder: "all"
  "6.0.1":
    folder: "all"
  "6.0":
    folder: "all"
  "5.1.3":
    folder: "all"
  "5.1":
    folder: "all"
  "5.0.3":
    folder: "all"
  "5.0":
    folder: "all"
  "4.4.4":
    folder: "all"
  "4.4.3":
    folder: "all"
  "4.4":
    folder: "all"
  "4.3.2":
    folder: "all"
  "4.2.1":
    folder: "all"
