versions:
  "20231101":
    folder: all
  "20230901":
    folder: all
  "20230801":
    folder: all
  "20230701":
    folder: all
  "20230602":
    folder: all
  "20230301":
    folder: all
  "20230201":
    folder: all
  "20221201":
    folder: all
  "20220601":
    folder: all
  "20220201":
    folder: all
  "20211101":
    folder: all
  "20210901":
    folder: all
