versions:
  "20220601":
    folder: all
  "20220201":
    folder: all
  "20211101":
    folder: all
  "20210901":
    folder: all
  "20210601":
    folder: all
  "20210401":
    folder: all
  "20210202":
    folder: all
  "20201101":
    folder: all
  "20201001":
    folder: all
  "20200801":
    folder: all
  "20200701":
    folder: all
  "20200601":
    folder: all
  "20200501":
    folder: all
  "20200401":
    folder: all
  "20200301":
    folder: all
  "20191101":
    folder: all
