versions:
  "1.1.0":
    folder: all
  "1.0.7":
    folder: all
  "1.0.6":
    folder: all
  "1.0.5":
    folder: all
  "1.0.4":
    folder: all
  "1.0.3":
    folder: all
  "1.0.2":
    folder: all
  "1.0.1":
    folder: all
  "1.0.0":
    folder: all
  "0.17.0":
    folder: all
  "0.12.2":
    folder: all
