versions:
  "1.8.0":
    folder: all
  "1.7.3":
    folder: all
  "1.7.2":
    folder: all
  "1.7.1":
    folder: all
  "1.7.0":
    folder: all
  "1.6.0":
    folder: all
  "1.5.2":
    folder: all
  "1.5.1":
    folder: all
  "1.3.2":
    folder: all
