versions:
  "1.8.4":
    folder: all
  "1.8.3":
    folder: all
  "1.8.2":
    folder: all
  "1.8.1":
    folder: all
  "1.8.0":
    folder: all
  "1.7.1":
    folder: all
  "1.7.0":
    folder: all
  "1.6.2":
    folder: all
  "1.6.1":
    folder: all
  "1.6.0":
    folder: all
  "1.5.6":
    folder: all
