versions:
  "1.3.268.0":
    folder: all
  "1.3.261.1":
    folder: all
  "1.3.250.1":
    folder: all
  "1.3.246.1":
    folder: all
  "1.3.243.0":
    folder: all
  "1.3.239.0":
    folder: all
  "1.3.236.0":
    folder: all
  "1.3.231.1":
    folder: all
  "1.3.224.1":
    folder: all
  "1.3.224.0":
    folder: all
  "20210115":
    folder: all
