versions:
  "1.3.224.0":
    folder: all
  "1.3.216.0":
    folder: all
  "1.3.211.0":
    folder: all
  "1.3.204.0":
    folder: all
  "cci.20211113":
    folder: all
  "cci.20210930":
    folder: all
  "cci.20210823":
    folder: all
  "cci.20210621":
    folder: all
  "20210115":
    folder: all
  "20200917":
    folder: all
  "20200629":
    folder: all
  "20200519":
    folder: all
  "20200403":
    folder: all
