versions:
  "1.4.0":
    folder: all
  "1.3.2":
    folder: all
  "1.3.1":
    folder: all
  "1.3.0":
    folder: all
  "1.2.3":
    folder: all
  "1.2.2":
    folder: all
  "1.2.1":
    folder: all
  "1.2.0":
    folder: all
  "1.1.8":
    folder: all
