versions:
  "3.15.7":
    folder: "3.x.x"
  "3.16.9":
    folder: "3.x.x"
  "3.17.5":
    folder: "3.x.x"
  "3.18.6":
    folder: "3.x.x"
  "3.19.8":
    folder: "3.x.x"
  "3.20.0":
    folder: "3.x.x"
  "3.20.1":
    folder: "3.x.x"
  "3.20.2":
    folder: "3.x.x"
  "3.20.3":
    folder: "3.x.x"
  "3.20.4":
    folder: "3.x.x"
