versions:
  "3.19.8":
    folder: "3.x.x"
  "3.20.6":
    folder: "3.x.x"
  "3.21.7":
    folder: "3.x.x"
  "3.22.6":
    folder: "3.x.x"
  "3.23.5":
    folder: "3.x.x"
  "3.24.3":
    folder: "3.x.x"
  "3.25.0":
    folder: "3.x.x"
