versions:
  "3.15.7":
    folder: "3.x.x"
  "3.16.9":
    folder: "3.x.x"
  "3.17.5":
    folder: "3.x.x"
  "3.18.6":
    folder: "3.x.x"
  "3.19.8":
    folder: "3.x.x"
  "3.20.6":
    folder: "3.x.x"
  "3.21.4":
    folder: "3.x.x"
  "3.22.0":
    folder: "3.x.x"
