versions:
  "3.19.8":
    folder: "3.x.x"
  "3.20.6":
    folder: "3.x.x"
  "3.21.7":
    folder: "3.x.x"
  "3.22.5":
    folder: "3.x.x"
  "3.23.3":
    folder: "3.x.x"
  "3.24.0":
    folder: "3.x.x"
  "3.24.1":
    folder: "3.x.x"
