versions:
  "3.16.2":
    folder: "3.x.x"
  "3.16.3":
    folder: "3.x.x"
  "3.16.4":
    folder: "3.x.x"
  "3.16.5":
    folder: "3.x.x"
  "3.16.6":
    folder: "3.x.x"
  "3.16.7":
    folder: "3.x.x"
  "3.16.8":
    folder: "3.x.x"
  "3.17.0":
    folder: "3.x.x"
  "3.17.1":
    folder: "3.x.x"
  "3.17.2":
    folder: "3.x.x"
  "3.17.3":
    folder: "3.x.x"
  "3.17.4":
    folder: "3.x.x"
  "3.18.0":
    folder: "3.x.x"
  "3.18.1":
    folder: "3.x.x"
  "3.18.2":
    folder: "3.x.x"
