versions:
  "0.7.0":
    folder: v0.7
  "0.6.0":
    folder: all
  "0.5.1":
    folder: all
  "0.4.0":
    folder: all
  "0.3.0":
    folder: all
  "0.2.1":
    folder: all
  "0.2.0":
    folder: all
  "0.1.0":
    folder: 0.1.0
