versions:
  "1.8.0":
    folder: "all"
  "1.7.0":
    folder: "all"
  "1.6.0":
    folder: "all"
  "1.5.0":
    folder: "all"
  "1.4.0":
    folder: "all"
  "1.3.1":
    folder: "all"
  "1.3.0":
    folder: "all"
  "1.2.4":
    folder: "all"
  "1.2.3":
    folder: "all"
