versions:
  "1.33":
    folder: all
  "1.32":
    folder: all
  "1.31":
    folder: all
  "1.27":
    folder: all
  "1.26":
    folder: all
  "1.25":
    folder: all
  "1.24":
    folder: all
  "1.23":
    folder: all
  "1.21":
    folder: all
