versions:
  "1.3.1":
    folder: all
  "1.2.4":
    folder: all
  "1.2.2":
    folder: all
  "1.1.6":
    folder: all
  "1.1.5":
    folder: all
  "1.1.3":
    folder: all
  "1.0.6":
    folder: all
  "1.0.3":
    folder: all
