versions:
  "17.0.6":
    folder: all
  "17.0.4":
    folder: all
  "16.0.6":
    folder: all
  "15.0.7":
    folder: all
  "14.0.6":
    folder: all
  "13.0.1":
    folder: all
  "12.0.1":
    folder: all
  "11.1.0":
    folder: all
  "10.0.0":
    folder: all
  "9.0.1":
    folder: all
  "8.0.1":
    folder: all
