versions:
  "3.10.0":
    folder: all
  "3.9.0":
    folder: all
  "3.8.0":
    folder: all
  "3.7.0":
    folder: all
  "3.6.0":
    folder: all
  "3.5.0":
    folder: all
  "3.4.0":
    folder: all
  "3.3.0":
    folder: all
  "3.2.0":
    folder: all
  "3.1.0":
    folder: all
