versions:
  "1.89.0":
    folder: all
  "1.88.0":
    folder: all
  "1.87.0":
    folder: all
  "1.86.0":
    folder: all
  "1.85.0":
    folder: all
  "1.84.0":
    folder: all
  "1.83.0":
    folder: all
  "1.82.0":
    folder: all
  "1.81.0":
    folder: all
  "1.80.0":
    folder: all
  "1.79.0":
    folder: all
  "1.78.0":
    folder: all
