versions:
  "api.252005":
    folder: "all"
  "api.252004":
    folder: "all"
  "api.252003":
    folder: "all"
  "2.5.2":
    folder: "all"
  "2.5.1":
    folder: "all"
  "api.250014":
    folder: "all"
