versions:
  "1.1.11":
    folder: all
  "1.1.10":
    folder: all
  "1.1.9":
    folder: all
  "1.1.8":
    folder: all
  "1.1.6":
    folder: all
  "1.1.5":
    folder: all
  "1.1.4":
    folder: all
  "1.1.1":
    folder: all
  "1.1.0":
    folder: all
