versions:
  "2.8.4":
    folder: all
  "2.9.2":
    folder: all
  "2.10":
    folder: all
  "3.0.1":
    folder: all
  "3.1":
    folder: all
  "3.2":
    folder: all
  "3.3.4":
    folder: all
  "3.4.1":
    folder: all
  "3.5":
    folder: all
  "3.6":
    folder: all
  "3.7":
    folder: all
