versions:
  2.9.2:
    folder: 2.x.x
  2.11.0:
    folder: 2.x.x
  2.11.1:
    folder: 2.x.x
  2.11.3:
    folder: 2.x.x
  2.12.0:
    folder: 2.x.x
  2.12.1:
    folder: 2.x.x
  2.12.2:
    folder: 2.x.x
  2.12.3:
    folder: 2.x.x
  2.12.4:
    folder: 2.x.x
  2.13.0:
    folder: 2.x.x
  2.13.1:
    folder: 2.x.x
  2.13.2:
    folder: 2.x.x
  2.13.3:
    folder: 2.x.x
  2.13.4:
    folder: 2.x.x
  2.13.6:
    folder: 2.x.x
  "2.13.7":
    folder: 2.x.x
