versions:
  "3.1.0":
    folder: all
  "3.0.4":
    folder: all
  "3.0.3":
    folder: all
  "3.0.2":
    folder: all
  "3.0.1":
    folder: all
  "3.0.0":
    folder: all
  "2.1.5":
    folder: all
  "2.0.6":
    folder: all
