versions:
  "0.3.7":
    folder: all
  "0.4.0":
    folder: all
  "0.5.0":
    folder: all
  "0.9.1":
    folder: all
  "0.10.0":
    folder: all
  "0.11.0":
    folder: all
  "0.12.0":
    folder: all
