versions:
  "2.12.1":
    folder: all
  "2.13.0":
    folder: all
  "2.14.0":
    folder: all
  "2.15.0":
    folder: all
  "2.16.0":
    folder: all
  "2.17.0":
    folder: all
  "2.17.1":
    folder: all
  "2.17.2":
    folder: all
  "2.17.3":
    folder: all
  "2.18.0":
    folder: all
  "2.18.1":
    folder: all
  "2.18.2":
    folder: all
  "2.19.1":
    folder: all
  "2.19.2":
    folder: all
