versions:
  "2.17.3":
    folder: all
  "2.18.2":
    folder: all
  "2.19.1":
    folder: all
  "2.19.2":
    folder: all
  "2.19.3":
    folder: all
  "2.19.4":
    folder: all
  "3.0.0":
    folder: all
  "3.1.0":
    folder: all
  "3.1.1":
    folder: all
  "3.2.0":
    folder: all
  "3.3.0":
    folder: all
