versions:
  # 3.0.x releases
  3.1.1:
    folder: "3.x.x"
  3.1.0:
    folder: "3.x.x"
  3.0.9:
    folder: "3.x.x"
  3.0.8:
    folder: "3.x.x"
  3.0.7:
    folder: "3.x.x"
  3.0.5:
    folder: "3.x.x"

  # 1.1.1x releases
  1.1.1u:
    folder: "1.x.x"
  1.1.1t:
    folder: "1.x.x"
  1.1.1s:
    folder: "1.x.x"
  1.1.1q:
    folder: "1.x.x"
  # 1.1.0x releases
  1.1.0l:
    folder: "1.x.x"
  # 1.0.2x releases
  1.0.2u:
    folder: "1.x.x"
