versions:
  "3.6.1":
    folder: "3.x.x"
  "3.5.5":
    folder: "3.x.x"
  "3.4.4":
    folder: "3.x.x"
  "3.3.6":
    folder: "3.x.x"
  "3.2.6":
    folder: "3.x.x"
  "3.1.2":
    folder: "3.x.x"
  "3.0.19":
    folder: "3.x.x"
  "1.1.1w":
    folder: "1.x.x"
