versions:
  "3.3.1":
    folder: "3.x.x"
  "3.2.2":
    folder: "3.x.x"
  "3.2.1":
    folder: "3.x.x"
  "3.1.6":
    folder: "3.x.x"
  "3.1.5":
    folder: "3.x.x"
  "3.0.14":
    folder: "3.x.x"
  "3.0.13":
    folder: "3.x.x"
  "1.1.1w":
    folder: "1.x.x"
