versions:
  "3.4.1":
    folder: "3.x.x"
  "3.3.3":
    folder: "3.x.x"
  "3.2.4":
    folder: "3.x.x"
  "3.1.8":
    folder: "3.x.x"
  "3.1.2":
    folder: "3.x.x"
  "3.0.16":
    folder: "3.x.x"
  "1.1.1w":
    folder: "1.x.x"
