versions:
  # 3.1.x releases
  3.1.3:
    folder: "3.x.x"
  3.1.2:
    folder: "3.x.x"
  3.1.1:
    folder: "3.x.x"
  # 3.0.x releases
  3.0.11:
    folder: "3.x.x"
  # 1.1.1x releases
  1.1.1w:
    folder: "1.x.x"
  1.1.1u:
    folder: "1.x.x"
  # 1.0.2x releases
  1.0.2u:
    folder: "1.x.x"
