versions:
  "3.6.0":
    folder: "3.x.x"
  "3.5.4":
    folder: "3.x.x"
  "3.4.3":
    folder: "3.x.x"
  "3.3.5":
    folder: "3.x.x"
  "3.2.6":
    folder: "3.x.x"
  "3.1.2":
    folder: "3.x.x"
  "3.0.18":
    folder: "3.x.x"
  "1.1.1w":
    folder: "1.x.x"
