versions:
  1.0.2s:
    folder: "all"
  1.0.2t:
    folder: "all"
  1.0.2u:
    folder: "all"
  1.1.0k:
    folder: "all"
  1.1.0l:
    folder: "all"
  1.1.1c:
    folder: "all"
  1.1.1d:
    folder: "all"
  1.1.1d.dssl1:
    folder: "all"
  1.1.1d.dssl2:
    folder: "all"
  1.1.1e:
    folder: "all"
  1.1.1f:
    folder: "all"
  1.1.1g:
    folder: "all"
  1.1.1h:
    folder: "all"
  1.1.1i:
    folder: "all"
  1.1.1j:
    folder: "all"
  1.1.1k:
    folder: "all"
