versions:
  "1.21.1":
    folder: all
  "1.21.0":
    folder: all
  "1.20.1":
    folder: all
  "1.20.0":
    folder: all
  "1.19.0":
    folder: all
  "1.18.1":
    folder: all
  "1.17.1":
    folder: all
