versions:
  "8.1.0":
    folder: all
  "8.0.5":
    folder: all
  "8.0.3":
    folder: all
  "7.5.0":
    folder: all
  "7.4.10":
    folder: all
  "7.4.9":
    folder: all
  "7.4.8":
    folder: all
  "7.4.6":
    folder: all
  "7.4.5":
    folder: all
  "7.4.4":
    folder: all
