versions:
  "2.7.7":
    folder: all
  "2.7.5":
    folder: all
  "2.7.4":
    folder: all
  "2.7.3":
    folder: all
  "2.7.2":
    folder: all
  "2.7.0":
    folder: all
  "2.6.10":
    folder: all
  "2.6.7":
    folder: all
  "2.6.4":
    folder: all
  "2.6.2":
    folder: all
  "2.6.0":
    folder: all
  "2.5.1":
    folder: all
  "2.5.0":
    folder: all
  "2.4.2":
    folder: all
