versions:
  "0.6.9":
    folder: all
  "0.6.1":
    folder: all
  "0.5.20":
    folder: all
  "0.5.19":
    folder: all
  "0.5.17":
    folder: all
  "0.5.13":
    folder: all
  "0.5.12":
    folder: all
