versions:
  "43.1":
    folder: all
  "42.0":
    folder: all
  "41.0":
    folder: all
  "40.0":
    folder: all
  "39.0":
    folder: all
  "38.0":
    folder: all
  "37.0":
    folder: all
  "35.0":
    folder: all
  "34.0":
    folder: all
  "32.1":
    folder: all
  "31.0":
    folder: all
  "30.0":
    folder: all
  "27.1":
    folder: all
  "27.0":
    folder: all
  "26.1":
    folder: all
