versions:
  "1.0.2":
    folder: all
  "1.0.1":
    folder: all
  "1.0.0":
    folder: all
  "0.10.4":
    folder: all
  "0.10.3":
    folder: all
  "0.10.1":
    folder: all
  "0.10.0":
    folder: all
  "0.9.1":
    folder: all
  "0.8.0":
    folder: all
  "0.7.0":
    folder: all
