versions:
  "1.9.10":
    folder: "all"
  "1.9.9":
    folder: "all"
  "1.9.8":
    folder: "all"
  "1.9.7":
    folder: "all"
  "1.9.6":
    folder: "all"
  "1.9.5":
    folder: "all"
  "1.9.4":
    folder: "all"
  "1.9.3":
    folder: "all"
  "1.9.2":
    folder: "all"
  "1.9.1":
    folder: "all"
  "1.9.0":
    folder: "all"
  "1.8.7":
    folder: "all"
