versions:
  "0.3.17":
    folder: all
  "0.3.15":
    folder: all
  "0.3.13":
    folder: all
  "0.3.12":
    folder: all
  "0.3.10":
    folder: all
  "0.3.9":
    folder: all
  "0.3.7":
    folder: all
