versions:
  "3.0.1":
    folder: all
  "3.0.0":
    folder: all
  "2.4.1":
    folder: all
  "2.4.0":
    folder: all
  "2.3.9":
    folder: all
  "2.3.8":
    folder: all
  "2.3.5":
    folder: all
  "2.3.4":
    folder: all
  "2.3.2":
    folder: all
  "2.3.1":
    folder: all
