versions:
  2.3.5:
    folder: 2.x.x
  2.3.6:
    folder: 2.x.x
  2.3.7:
    folder: 2.x.x
  2.3.8:
    folder: 2.x.x
  2.4.0:
    folder: 2.x.x
  2.4.1:
    folder: 2.x.x
  2.4.3:
    folder: 2.x.x
  2.4.4:
    folder: 2.x.x
  2.4.5:
    folder: 2.x.x
  2.4.6:
    folder: 2.x.x
  2.4.8:
    folder: 2.x.x
  "2.4.9":
    folder: 2.x.x
