versions:
  "2.8.0":
    folder: all
  "2.7.4":
    folder: all
  "2.7.3":
    folder: all
  "2.7.2":
    folder: all
  "2.7.1":
    folder: all
  "2.7.0":
    folder: all
  "2.6.0":
    folder: all
  "2.5.2":
    folder: all
  "2.5.1":
    folder: all
  "2.5.0":
    folder: all
  "2.4.4":
    folder: all
  "2.4.3":
    folder: all
  "2.4.2":
    folder: all
  "2.4.1":
    folder: all
  "2.4.0":
    folder: all
  "2.3.9":
    folder: all
  "2.3.4":
    folder: all
  "2.3.3":
    folder: all
  "2.3.2":
    folder: all
  "2.3.1":
    folder: all
  "2.3.0":
    folder: all
  "2.2.3":
    folder: all
  "2.2.2":
    folder: all
  "2.2.1":
    folder: all
  "2.2.0":
    folder: all
  "2.1.1":
    folder: all
  "2.1.0":
    folder: all
  "2.0.18":
    folder: all
  "2.0.16":
    folder: all
  "2.0.15":
    folder: all
  "2.0.14":
    folder: all
  "2.0.13":
    folder: all
  "2.0.12":
    folder: all
  "2.0.11":
    folder: all
  "2.0.10":
    folder: all
  "2.0.9":
    folder: all
  "2.0.8":
    folder: all
  "2.0.7":
    folder: all
  "2.0.6":
    folder: all
  "2.0.5":
    folder: all
  "2.0.4":
    folder: all
  "2.0.3":
    folder: all
  "2.0.2":
    folder: all
  "2.0.1":
    folder: all
  "2.0.0":
    folder: all
