versions:
  1.7.5:
    folder: all
  1.7.6:
    folder: all
  2.0.0:
    folder: all
  2.0.1:
    folder: all
  2.0.2:
    folder: all
  2.0.3:
    folder: all
  2.0.4:
    folder: all
  2.1.0:
    folder: all
  2.1.1:
    folder: all
  2.1.2:
    folder: all
  2.1.3:
    folder: all
  2.2.0:
    folder: all
  2.3.0:
    folder: all
