versions:
  1.7.6:
    folder: all
  2.0.4:
    folder: all
  2.1.3:
    folder: all
  2.2.0:
    folder: all
  2.3.0:
    folder: all
  2.4.0:
    folder: all
  2.4.1:
    folder: all
  2.5.0:
    folder: all
