versions:
  "3.1.23":
    folder: all
  "3.1.20":
    folder: all
  "3.1.18":
    folder: all
  "3.1.17":
    folder: all
  "3.1.16":
    folder: all
  "3.1.15":
    folder: all
  "3.1.12":
    folder: all
  "3.1.7":
    folder: all
  "3.1.5":
    folder: all
  "3.1.4":
    folder: all
  "3.1.3":
    folder: all
  "3.1.0":
    folder: all
  "3.0.1":
    folder: all
  "3.0.0":
    folder: all
  "2.0.34":
    folder: all
  "2.0.31":
    folder: all
  "2.0.30":
    folder: all
