versions:
  "9.0.1":
    folder: "all"
  "9.0.0":
    folder: "all"
  "8.2.1":
    folder: "all"
  "8.2.0":
    folder: "all"
  "8.1.1":
    folder: "all"
  "8.1.0":
    folder: "all"
  "8.0.1":
    folder: "all"
  "8.0.0":
    folder: "all"
  "7.2.1":
    folder: "all"
  "6.3.1":
    folder: "all"
