versions:
  "1.0.0":
    folder: all
  "1.1.0":
    folder: all
  "1.2.0":
    folder: all
  "1.3.0":
    folder: all
  "1.4.0":
    folder: all
  "1.5.0":
    folder: all
  "1.5.1":
    folder: all
  "1.6.0":
    folder: all
