versions:
  "r27c":
    folder: all
  "r27":
    folder: all
  "r26d":
    folder: all
  "r26c":
    folder: all
  "r26b":
    folder: all
  "r26":
    folder: all
  "r25c":
    folder: all
  "r25b":
    folder: all
  "r25":
    folder: all
  "r24":
    folder: all
  "r23c":
    folder: all
  "r23b":
    folder: all
  "r23":
    folder: all
  "r22b":
    folder: all
  "r22":
    folder: all
  "r21e":
    folder: all
  "r21d":
    folder: all
  "r20b":
    folder: all
  "r19c":
    folder: all
