versions:
  "r25":
    folder: all
  "r24":
    folder: all
  "r23c":
    folder: all
  "r23b":
    folder: all
  "r23":
    folder: all
  "r22b":
    folder: all
  "r22":
    folder: all
  "r21e":
    folder: all
  "r21d":
    folder: all
