versions:
  "1.5.1":
    folder: all
  "1.6.0":
    folder: all
  "1.7.0":
    folder: all
  "1.8.0":
    folder: all
  "1.8.1":
    folder: all
  "1.9.0":
    folder: all
  "1.10.0":
    folder: all
  "1.11.0":
    folder: all
  "1.12.0":
    folder: all
  "1.12.1":
    folder: all
  "1.13.0":
    folder: all
