versions:
  "2.0.0":
    folder: all
  "1.17.0":
    folder: all
  "1.16.0":
    folder: all
  "1.15.0":
    folder: all
  "1.14.0":
    folder: all
  "1.13.2":
    folder: all
  "1.13.1":
    folder: all
  "1.13.0":
    folder: all
  "1.12.1":
    folder: all
  "1.12.0":
    folder: all
  "1.11.0":
    folder: all
  "1.10.0":
    folder: all
