versions:
  "2.4.3":
    folder: all
  "2.5.0":
    folder: all
  "2.6.0":
    folder: all
  "2.6.1":
    folder: all
  "2.6.2":
    folder: all
  "2.7.0":
    folder: all
  "2.7.1":
    folder: all
  "2.8.1":
    folder: all
