versions:
  "2.13.4":
    folder: all
  "2.13.2":
    folder: all
  "2.13.1":
    folder: all
  "2.12.0":
    folder: all
  "2.11.1":
    folder: all
  "2.10.4":
    folder: all
  "2.10.1":
    folder: all
  "2.10.0":
    folder: all
  "2.9.2":
    folder: all
  "2.9.1":
    folder: all
  "2.8.1":
    folder: all
  "2.7.1":
    folder: all
