versions:
  "1.3.216.0":
    folder: all
  "1.3.211.0":
    folder: all
  "1.3.204.0":
    folder: all
  "2021.4":
    folder: all
  "2021.3":
    folder: all
  "2021.2":
    folder: all
  "2020.5":
    folder: all
  "2020.3":
    folder: all
  "2019.2":
    folder: all
