versions:
  "2.2.2":
    folder: all
  "2.2.0":
    folder: all
  "2.1.0":
    folder: all
  "2.0.4":
    folder: all
  "2.0.3":
    folder: all
  "2.0.1":
    folder: all
  "1.1.0":
    folder: all
  "1.0.2":
    folder: all
  "0.9.7":
    folder: all
