versions:
  "2.0.3":
    folder: all
  "2.0.1":
    folder: all
  "1.1.0":
    folder: all
  "1.0.2":
    folder: all
  "0.9.7":
    folder: all
  "0.8.2":
    folder: all
  "0.7.1":
    folder: all
  "0.6.1":
    folder: all
  "0.5.0":
    folder: all
  "0.4.7":
    folder: all
