versions:
  "3.5.0":
    folder: all
  "3.3.0":
    folder: all
  "3.2.3":
    folder: all
  "3.2.2":
    folder: all
  "3.2.1":
    folder: all
  "3.2.0":
    folder: all
  "3.1.8":
    folder: all
  "3.0.1":
    folder: all
  "2.2.3":
    folder: all
