versions:
  "3.11.2":
    folder: all
  "3.10.1":
    folder: all
  "3.10.0":
    folder: all
  "3.9.3":
    folder: all
  "3.9.2":
    folder: all
  "3.9.1":
    folder: all
  "3.8.0":
    folder: all
  "3.7.0":
    folder: all
  "3.6.4":
    folder: all
  "3.5.0":
    folder: all
  "3.3.0":
    folder: all
  # fastgltf requires simdjson/3.2.0
  "3.2.0":
    folder: all
