versions:
  "2.17.1":
    folder: all
  "2.17.0":
    folder: all
  "2.16.2":
    folder: all
  "2.16.0":
    folder: all
  "2.15.0":
    folder: all
  "2.14.2":
    folder: all
  "2.13.4":
    folder: all
  "2.12.1":
    folder: all
  "2.11.1":
    folder: all
  "2.10.3":
    folder: all
  "2.9.3":
    folder: all
  "2.8.2":
    folder: all
