versions:
  "0.15.9":
    folder: all
  "0.15.4":
    folder: all
  "0.15.3":
    folder: all
  "0.14.10":
    folder: all
  "0.14.6":
    folder: all
  "0.13.8":
    folder: all
  "0.13.7":
    folder: all
