versions:
  "2.9.2":
    folder: all
  "2.7.0":
    folder: all
  "2.6.0":
    folder: all
  "2.5.1":
    folder: all
  "2.4.0":
    folder: all
  "2.3.0":
    folder: all
  "2.2.0":
    folder: all
  "2.1.0":
    folder: all
  "2.0.0":
    folder: all
  "1.7.0":
    folder: all
