versions:
  "1.6.43":
    folder: all
  "1.6.42":
    folder: all
  "1.6.41":
    folder: all
  "1.6.40":
    folder: all
  "1.6.39":
    folder: all
  "1.6.38":
    folder: all
  "1.6.37":
    folder: all
  "1.6.32":
    folder: all
  "1.5.30":
    folder: all
