versions:
  "1.6.48":
    folder: all
  "1.6.47":
    folder: all
  "1.6.46":
    folder: all
  "1.6.45":
    folder: all
  "1.6.44":
    folder: all
  "1.6.43":
    folder: all
  "1.6.42":
    folder: all
  "1.6.41":
    folder: all
  "1.6.40":
    folder: all
  "1.6.39":
    folder: all
  "1.6.38":
    folder: all
  "1.6.37":
    folder: all
  "1.6.32":
    folder: all
  "1.5.30":
    folder: all
