versions:
  "3.23.2":
    folder: "all"
  "3.23.0":
    folder: "all"
  "3.20.1":
    folder: "all"
  "3.19.0":
    folder: "all"
  "3.17.2":
    folder: "all"
  "3.17.1":
    folder: "all"
  "3.16.0":
    folder: "all"
  "3.15.0":
    folder: "all"
  "3.14.1":
    folder: "all"
  "3.14.0":
    folder: "all"
  "3.12.0":
    folder: "all"
  "3.11.1":
    folder: "all"
