name: "[service] Alert Community"

on:
  pull_request_target:
    types: [opened]

env:
  PYVER: "3.10"

jobs:
  comment:
    if: github.repository == 'conan-io/conan-center-index'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - uses: ./.github/actions/alert-community
        with:
          files: "docs/*/*"
          reviewers: "@prince-chrismc @MartinDelille @Croydon"

      - uses: ./.github/actions/alert-community
        with:
          files: ".github/*/*"
          reviewers: "@ericLemanissier @prince-chrismc @Croydon"

      - uses: ./.github/actions/alert-community
        with:
          files: "linter/*/*"
          reviewers: "@ericLemanissier @prince-chrismc @Croydon"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/aaf/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/abseil/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/avahi/*/*"
          reviewers: "@jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/b2/*/*"
          reviewers: "@grafikrobot"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/bandit/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/benchmark/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/boost/*/*"
          reviewers: "@grafikrobot @Hopobcn @jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/boost-ext-ut/*/*"
          reviewers: "@jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/bzip2/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/cereal/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/cmake/*/*"
          reviewers: "@Croydon"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/cppcheck/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/create-dmg/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/dbus/*/*"
          reviewers: "@jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/double-conversion/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/eigen/*/*"
          reviewers: "@jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/elfio/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/ffmpeg/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/fmt/*/*"
          reviewers: "@Hopobcn @jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/folly/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/foxi/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/fp16/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/g3log/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/gflags/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/glew/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/glfw/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/glog/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/gtest/*/*"
          reviewers: "@Hopobcn @jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/gtk/*/*"
          reviewers: ""

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/imgui/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/implot/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/jemalloc/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libalsa/*/*"
          reviewers: "@jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libarchive/*/*"
          reviewers: "@jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libbacktrace/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libcap/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libcurl/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libdwarf/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libelf/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libevent/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libffi/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libiberty/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libiconv/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libltc/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libpng/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libsodium/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libspatialite/*/*"
          reviewers: "@jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libunwind/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libuuid/*/*"
          reviewers: "@jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libxml2/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/llvm-core/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/lyra/*/*"
          reviewers: "@grafikrobot"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/lz4/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/ms-gsl/*/*"
          reviewers: "@jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/nlohmann_json/*/*"
          reviewers: "@Hopobcn @jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/onnx/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/openapi-generator/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/opengl/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/opengl-registry/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/openssl/*/*"
          reviewers: "@Hopobcn @Croydon"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/protobuf/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/psimd/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/qt/*/*"
          reviewers: "@ericLemanissier @jwillikers @MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/quazip/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/rtmidi/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/sentry-*/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/shapelib/*/*"
          reviewers: "@jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/snappy/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/uncrustify/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/wayland/*/*"
          reviewers: "@jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/wayland-protocols/*/*"
          reviewers: "@jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/xkbcommon/*/*"
          reviewers: "@jwillikers"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/xorg/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/yaml-cpp/*/*"
          reviewers: "@jwillikers @MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/xz_utils/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/zlib/*/*"
          reviewers: "@Hopobcn"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/zstd/*/*"
          reviewers: "@Hopobcn"
