name: "[service] Alert Community"

on:
  pull_request_target:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: ./.github/actions/alert-community
        with:
          files: "docs/*/*"
          reviewers: "@prince-chrismc @MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: ".github/*/*"
          reviewers: "@ericLemanissier @prince-chrismc"

      - uses: ./.github/actions/alert-community
        with:
          files: "linter/*/*"
          reviewers: "@ericLemanissier @prince-chrismc"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/aaf/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/b2/*/*"
          reviewers: "@grafikrobot"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/bandit/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/cppcheck/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/create-dmg/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/ffmpeg/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/gtk/*/*"
          reviewers: "@ericLemanissier"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/libltc/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/lyra/*/*"
          reviewers: "@grafikrobot"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/openapi-generator/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/opengl-registry/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/qt/*/*"
          reviewers: "@ericLemanissier @MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/quazip/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/rtmidi/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/sentry-*/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/uncrustify/*/*"
          reviewers: "@MartinDelille"

      - uses: ./.github/actions/alert-community
        with:
          files: "recipes/yaml-cpp/*/*"
          reviewers: "@MartinDelille"
