name: glib CI

on:
  pull_request:
    paths:
      - 'recipes/glib/all/**'
      - 'build.py'
      - '.github/workflows/glib.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/glib/all/**'
      - 'build.py'
      - '.github/workflows/glib.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}
  CONAN_REFERENCE: 'glib/2.64.0'
  IS_PURE_C: true

jobs:
  glib:
    strategy:
      matrix:
        build: ['linux-gcc8']
        include:
          - build: 'linux-gcc8'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '8'
            docker_image: 'trassiross/conan-gcc8'
            build_types: 'Release'
            archs: 'x86_64'
            conan_options: '
              glib:with_pcre=False,
              glib:with_elf=False,
              glib:with_mount=False,
              glib:with_selinux=False
              '
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf input
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/glib/all
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          CONAN_OPTIONS: ${{ matrix.conan_options }}
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
