name: Auto Label Conflicts
on:
  push:
    branches: [master]
  pull_request_target:
    branches: [master]

permissions: # Required to add labels
  issues: write
  pull-requests: write

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - uses: prince-chrismc/label-merge-conflicts-action@comment-on-pr
        with:
          conflict_label_name: "has conflicts"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          max_retries: 5
          wait_ms: 10000
          detect_merge_changes: true
