name: libcurl CI

on:
  pull_request:
    paths:
      - 'recipes/libcurl/all/**'
      - 'build.py'
      - '.github/workflows/libcurl.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/libcurl/all/**'
      - 'build.py'
      - '.github/workflows/libcurl.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}
  IS_PURE_C: true

jobs:
  libcurl:
    strategy:
      matrix:
        build: ['linux-gcc7', 'windows-2019-release', 'macos']
        libcurl_versions: ['7.64.1']
        include:
          - build: 'linux-gcc7'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '7'
            docker_image: 'conanio/gcc7'
            build_types: 'Release,Debug'
            archs: 'x86,x86_64'
          - build: 'windows-2019-release'
            os: 'windows-2019'
            build_types: 'Release'
            compiler: 'vs'
            compiler_version: '16'
            vs_runtimes: 'MD,MT'
            archs: 'x86_64'
          - build: 'macos'
            os: 'macos-latest'
            build_types: 'Release,Debug'
            archs: 'x86_64'
            compiler: 'apple_clang'
            compiler_version: '11.0'
            xcode_version: '11.3.1'
            options: 'libcurl:darwin_ssl=False'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install automake
        if: matrix.os == 'macos-latest'
        run: brew install automake
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/libcurl/all
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          CONAN_OPTIONS: ${{ matrix.options }}
          CONAN_REFERENCE: 'libcurl/${{ matrix.libcurl_versions }}'
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
