name: libiconv CI

on:
  pull_request:
    paths:
      - 'recipes/libiconv/**'
      - 'build.py'
      - '.github/workflows/libiconv.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/libiconv/**'
      - 'build.py'
      - '.github/workflows/libiconv.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}
  IS_PURE_C: true

jobs:
  libiconv:
    strategy:
      matrix:
        build: ['linux-gcc4.8', 'linux-gcc7', 'linux-gcc9', 'macos']
        libiconv_versions: ['1.15']
        include:
          - build: 'linux-gcc4.8'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '4.8'
            docker_image: 'conanio/gcc48'
            build_types: 'Release,Debug'
            archs: 'x86,x86_64'
          - build: 'linux-gcc7'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '7'
            docker_image: 'conanio/gcc7'
            build_types: 'Release,Debug'
            archs: 'x86,x86_64'
          - build: 'linux-gcc9'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '9'
            docker_image: 'conanio/gcc9'
            build_types: 'Release,Debug'
            archs: 'x86,x86_64'          
          - build: 'macos'
            os: 'macos-latest'
            build_types: 'Release,Debug'
            archs: 'x86_64'
            compiler: 'apple_clang'
            compiler_version: '11.0'
            xcode_version: '11.3.1'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/libiconv/all
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          CONAN_REFERENCE: libiconv/${{ matrix.libiconv_versions }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
