name: run linters

on:
  pull_request:

jobs:
  lint:
    env:
      CONAN_YAMLLINT_WERR: 1
      CONAN_PYLINT_WERR: 1
    strategy:
      fail-fast: false
      matrix:
        hook: ["yaml_linter", "recipe_linter"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - run: "pip3 install conan yamllint packaging pylint==2.10.2 astroid"

      - name: install hook
        run: |
          conan config install https://github.com/conan-io/hooks.git
          conan config set hooks.${{ matrix.hook }}

      - name: run lint
        run:  |
          echo "::add-matcher::.github/${{ matrix.hook }}.json"
          python3 .github/runlint.py
