name: mesa CI

on:
  pull_request:
    paths:
      - 'recipes/mesa/all/**'
      - 'build.py'
      - '.github/workflows/mesa.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/mesa/all/**'
      - 'build.py'
      - '.github/workflows/mesa.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}
  IS_PURE_C: true

jobs:
  mesa:
    strategy:
      matrix:
        build: ['macos']
        mesa_versions: ['19.3.1']
        include:
          - build: 'macos'
            os: 'macos-latest'
            build_types: 'Release,Debug'
            archs: 'x86_64'
            compiler: 'apple_clang'
            compiler_version: '11.0'
            xcode_version: '11.3.1'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install pkg-config
        if: matrix.os == 'macos-latest'
        run: brew install pkg-config
      - name: Install bison
        if: matrix.os == 'macos-latest'
        run: brew install bison
      - name: Install flex
        if: matrix.os == 'macos-latest'
        run: brew install flex
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/mesa/all
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          CONAN_REFERENCE: 'mesa/${{ matrix.mesa_versions }}'
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
