name: openssl CI

on:
  pull_request:
    paths:
      - 'recipes/openssl/all/**'
      - 'build.py'
      - '.github/workflows/openssl.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/openssl/all/**'
      - 'build.py'
      - '.github/workflows/openssl.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}
  IS_PURE_C: true

jobs:
  openssl:
    strategy:
      matrix:
        build: ['linux-gcc8', 'macos', 'windows-2019-release', 'windows-2019-debug']
        openssl_versions: ['1.1.1d']
        include:
          - build: 'linux-gcc8'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '8'
            docker_image: 'trassiross/conan-gcc8'
            build_types: 'Release'
            archs: 'x86_64'
          - build: 'macos'
            os: 'macos-10.15'
            deployment-target: '10.14'
            build_types: 'Release'
            archs: 'x86_64'
            compiler: 'apple_clang'
            compiler_version: '11.0'
            xcode_version: '11.4'
          - build: 'windows-2019-release'
            os: 'windows-2019'
            build_types: 'Release'
            compiler: 'vs'
            compiler_version: '16'
            vs_runtimes: 'MD,MT'
            archs: 'x86'
          - build: 'windows-2019-debug'
            os: 'windows-2019'
            build_types: 'Debug'
            compiler: 'vs'
            compiler_version: '16'
            vs_runtimes: 'MDd,MTd'
            archs: 'x86'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/openssl/all
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment-target }}
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          CONAN_REFERENCE: openssl/${{ matrix.openssl_versions }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
