name: opencv-2.4.13.5 CI

on:
  pull_request:
    paths:
      - 'recipes/opencv/2.4.13.5/**'
      - 'build.py'
      - '.github/workflows/opencv-2.4.13.5.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/opencv/2.4.13.5/**'
      - 'build.py'
      - '.github/workflows/opencv-2.4.13.5.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}
  CONAN_REFERENCE: 'opencv/2.4.13.5'
  IS_PURE_C: false

jobs:
  opencv:
    strategy:
      matrix:
        build: ['linux-gcc8', 'macos']
        include:
          - build: 'linux-gcc8'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '8'
            docker_image: 'trassiross/conan-gcc8'
            build_types: 'Release'
            archs: 'x86_64'
          - build: 'macos'
            os: 'macos-10.15'
            deployment-target: '10.14'
            build_types: 'Release'
            archs: 'x86_64'
            compiler: 'apple_clang'
            compiler_version: '11.0'
            xcode_version: '11.4'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install gtk+
        if: matrix.os == 'macos-10.15'
        run: brew install gtk+
      - name: Install gtk+
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y libgtk2.0-dev
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/opencv/2.4.13.5
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment-target }}
          # these are taken for macOS config, linux one may be different!
          CONAN_OPTIONS: '
            opencv:jasper=False,
            opencv:openexr=False,
            opencv:tiff=False
            '
          CONAN_SHARED_OPTION_NAME: False
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
