name: qt-5.14.1 CI

on:
  pull_request:
    paths:
      - 'recipes/qt/5.14.1/**'
      - 'build.py'
      - '.github/workflows/qt-5.14.1.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/qt/5.14.1/**'
      - 'build.py'
      - '.github/workflows/qt-5.14.1.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}
  IS_PURE_C: true # qt builds too long to wait for both libstdc++ and libstdc++11
  CONAN_REFERENCE: qt/5.14.1

jobs:
  qt_5_14_1:
    env:
      COMMON_CONAN_OPTIONS: '
      qt:openssl=True,
      qt:qtimageformats=True,
      qt:qtmultimedia=True,
      qt:qtscript=True,
      qt:qtsvg=True,
      qt:qttools=True,

      qt:with_glib=False,
      qt:with_harfbuzz=False,
      qt:with_icu=False,
      qt:with_mysql=False,
      qt:with_pcre2=False,
      qt:with_sdl2=False,
      qt:with_zstd=False
      '
    strategy:
      matrix:
        build: ['linux-gcc8', 'macos']
        include:
          - build: 'linux-gcc8'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '8'
            docker_image: 'trassiross/conan-gcc8'
            build_types: 'Release'
            archs: 'x86_64'
            conan_options: ', qt:qtx11extras=True'
          - build: 'macos'
            os: 'macos-10.15'
            deployment-target: '10.14'
            build_types: 'Release'
            archs: 'x86_64'
            conan_options: ', qt:with_builtin_libs=True'
            compiler: 'apple_clang'
            compiler_version: '11.0'
            xcode_version: '11.4'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/qt/5.14.1
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment-target }}
          CONAN_SHARED_OPTION_NAME: False
          CONAN_OPTIONS: ${{ env.COMMON_CONAN_OPTIONS }} ${{ matrix.conan_options }}
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
