name: Win32 vc142 Release

on:
  pull_request:
    paths:
      - 'recipes/**'
      - 'builder/**'
      - '.github/workflows/win32-vc142-release.yml'
      - 'trassir/win32-vc142/conanfile.txt'
      - 'trassir/win32-vc142/conanprofile.release'

  push:
    branches:
      - master
    paths:
      - 'recipes/**'
      - 'builder/**'
      - '.github/workflows/win32-vc142-release.yml'
      - 'trassir/win32-vc142/conanfile.txt'
      - 'trassir/win32-vc142/conanprofile.release'

env:
  LDAP_USERNAME: ${{ secrets.LDAP_USERNAME }}
  LDAP_PASSWORD: ${{ secrets.LDAP_PASSWORD }}
  REMOTES_USERNAME: ${{ secrets.CUSTOM_USERNAME }}
  REMOTES_PASSWORD: ${{ secrets.CUSTOM_PASSWORD }}
  REMOTES_MASTER: ${{ secrets.REMOTES_MASTER }}
  REMOTES_STAGING: ${{ secrets.REMOTES_STAGING }}
  IS_PURE_C: true

jobs:
  conan:
    runs-on: windows-2019
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Upload
        run: |
          pip install --upgrade conan
          python sources/builder/build.py
        env:
          PYTHONUNBUFFERED: "true"
          CONAN_TXT: trassir/win32-vc142/conanfile.txt
          CONAN_PROFILE: trassir/win32-vc142/conanprofile.release
