name: xkbcommon CI

on:
  pull_request:
    paths:
      - 'recipes/xkbcommon/all/**'
      - 'build.py'
      - '.github/workflows/xkbcommon.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/xkbcommon/all/**'
      - 'build.py'
      - '.github/workflows/xkbcommon.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}
  CONAN_DOCKER_ENTRY_SCRIPT: sudo apt-get update && sudo apt-get install -y bison pkg-config
  IS_PURE_C: true

jobs:
  xkbcommon:
    strategy:
      matrix:
        build: ['linux-gcc8']
        xkbcommon_versions: ['0.10.0']
        include:
          - build: 'linux-gcc8'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '8'
            docker_image: 'trassiross/conan-gcc8'
            build_types: 'Release'
            archs: 'x86_64'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/xkbcommon/all
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          CONAN_SHARED_OPTION_NAME: False
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          CONAN_REFERENCE: xkbcommon/${{ matrix.xkbcommon_versions }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
