versions:
  "3.10.2":
    folder: all
  "3.10.1":
    folder: all
  "3.8.1":
    folder: all
  "3.8.0":
    folder: all
  "3.7.2":
    folder: all
  "3.7.0":
    folder: all
  "3.6.7":
    folder: all
  "3.6.6":
    folder: all
  "3.6.2":
    folder: all
  "3.6.1":
    folder: all
