versions:
  "1.4.1":
    folder: all
  "1.4.0":
    folder: all
  "1.3.1":
    folder: all
  "1.3.0":
    folder: all
  "1.2.1":
    folder: all
  "1.1.0":
    folder: all
  "1.0.3":
    folder: all
  "1.0.1":
    folder: all
  "0.10.0":
    folder: all
